### PR TITLE
Replacement of caret.js/atwho.js by using Boostrap typeahead in search/userlist

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
Do we still need the files? or can you removed it also

**Comment by xillibit** [comment]
This PR is the first part, i need to do the same change on quick reply/message textarea because it use caret.js/atwho.js to show smilies list in the github way

**Comment by xillibit** [comment]
@rich20 or @810  : is-it working for you ?

**Comment by rich20** [comment]
Previously has been loaded: caret.js, atwho.js and bootstrap-min.js
Now only bootstrap-min.js
is it what you mean?

**Comment by xillibit** [comment]
Now on search and userlist the auto-suggest for username is using bootstrap ahead instead caret.js, atwho.js, so just check that auto-suggest work

**Comment by rich20** [comment]
auto.suggest dos not work for me

**Comment by xillibit** [comment]
For me ti works : http://screencast.com/t/HojiACHGRDo

**Comment by 810** [comment]
it works only when login

**Comment by xillibit** [comment]
It has been always like that even in blue eagle

**Comment by rich20** [comment]
> it works only when login

You're right. I had tested as guest.

**Comment by 810** [comment]
ok then its fine, you can start part2

**Pull request merged**
