### PR TITLE
Remove subscriptions when perm block from site #5945

### PR DESCRIPTION
**Pull request by 810**
@rich20 @sshcli please test if all subscriptions are still working.

#5945 

If joomla user is blocked, you should not get any email anymore.

### CODE REVIEW

**Comment by sshcli** [comment]
Test Results = ❌Fail 

**What is good / working?**
After apply patch, the blocked user does not receive email notifications

**What is wrong/not working?**
You get these errors when quick reply the topic:
```
0 Unsupported operand types
PHP Notice:  Undefined variable: userids in /home/username/libraries/kunena/access.php on line 1037
PHP Warning:  array_flip() expects parameter 1 to be array, null given in /home/username/libraries/kunena/access.php on line 877
PHP Warning:  array_intersect_key(): Argument #2 is not an array in /home/username/libraries/kunena/access.php on line 877
```

**Review by sshcli — COMMENTED** [review]
Test Results = ❌Fail 

**What is good / working?**
After apply patch, the blocked user does not receive email notifications

**What is wrong/not working?**
You get these errors when quick reply the topic:
```
0 Unsupported operand types
PHP Notice:  Undefined variable: userids in /home/username/libraries/kunena/access.php on line 1037
PHP Warning:  array_flip() expects parameter 1 to be array, null given in /home/username/libraries/kunena/access.php on line 877
PHP Warning:  array_intersect_key(): Argument #2 is not an array in /home/username/libraries/kunena/access.php on line 877
```

**Comment by 810** [comment]
@sshcli please try again, should now work

**Comment by sshcli** [comment]
Test Results = ✔️ Pass / Success / OK

**Pull request merged**
