### PR TITLE
Submit button is enabled during upload process #4429

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #4429  .

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] If the upload is to big, the Submit button remains inactive (also after click on Remove File)

You must refresh the page, if you want to use the submit button. But after refresh the text field is empty again.

**Comment by xillibit** [comment]
Do-you have browsed the file on your filesystem or just put in the web interface by drag&drop ?

**Comment by rich20** [comment]
- [ ] Upload with Drag&Drop - the Submit button remains enabled during the upload process
- [ ] Upload with Add button - the Submit button remains inactive after abort (its only the message "Attachment image size exceed limit allowed by configuration")

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Upload with Drag&Drop - Success
- [x] Upload with Add button - Success

**Pull request merged**
