### PR TITLE
Fix: replaced BS visible-xs with BS5 equivalent + category on recent …

### PR DESCRIPTION
**Pull request by Ruud68**
…posts

Pull Request for Issue #9463 . 
 
#### Summary of Changes 
replaced old BS class instances of 'visible-xs' with  new BS5 'd-block d-sm-none'
 added category on recent posts list

#### Testing Instructions
@rich20

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Recent Topics view
- [ ] Recent Posts view

If you click on profile (recent posts view) it lacks the category
 
g34246

**Comment by Ruud68** [comment]
hi @rich, can you turn on debugging and tell me which layout file this is? My development forum lacks some views mainly due to lack of categories (nested) and content, so for me this is the proverbal needle in the haystack I am looking for :)

**Comment by rich20** [comment]
I'm not a developer, but I think, between line 103 and 104 it lacks this code:
`			<span class="ktopic-category"><?php echo Text::sprintf('COM_KUNENA_CATEGORY_X', $this->getCategoryLink($topic->getCategory(), null, null, KunenaTemplate::getInstance()->tooltips())); ?></span>
			<br>`
https://github.com/Kunena/Kunena-Forum/blob/8009eb8bcea936819825510a77fbdb3096091a8d/src/site/template/aurelia/layouts/message/row/default.php#L103
.
image1210

**Comment by Ruud68** [comment]
@rich20 Thanks, that help a lot :)
There are so many files that it is hard to find out based on a (partial) screen capture what file it is that needs editing.
anyway, just updated the file you pointed to.

**Comment by rich20** [comment]
Can you check the code please?  I get now:

Message/Row: Property "topic" is not defined in /.../components/com_kunena/template/aurelia/layouts/message/row/default.php on line 100
Layout was rendered in /.../components/com_kunena/template/aurelia/layouts/message/list/default.php on line 142

**Comment by Ruud68** [comment]
Ok, so did a small change here, can you test again? if it display okay, can you also verify that the category link works (redirects to the (correct) category?
I cannot test myself :(

**Comment by rich20** [comment]
Thank you, everything successful
- [x] Recent Topics view
- [x] Recent Posts view

**Comment by Ruud68** [comment]
Thanks @rich20 for testing and pointing me in the right direction :)

**Pull request merged**
