### PR TITLE
Feature: ajax upload for avatar #3885 (set link on avatar to go to edit)

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by rich20** [comment]
#### Not sure if it's ok
- [x] When user click on avatar, it should go directly to edit profile <strike>and open the tab to change avatar</strike> (The link goes directly to the profile edit but you need a click on the tab to open the avatar options. For me it's ok.)

**Comment by xillibit** [comment]
I have modified to make it working too on categories index, do-you have an error on javascript console after to be redirected to profile page ?

**Comment by rich20** [comment]
<strike>Not directly a error, but this message I had not before:

jquery.min.js?fc02fca…:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.</strike>

**Comment by rich20** [comment]
> <strike>jquery.min.js?fc02fca…:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.</strike>

Sorry, this message comes aso without this fix if you click on Profile -> Edit. So is your fix for me now ok.

**Pull request merged**
