### PR TITLE
 Attachements: add insert all images to message #3172

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
when click insert all, the topic will be submitted.
and attach id is missing
[attachment=null]tweet_icon.png[/attachment] 
[attachment=null]27edd21a-6ac1-11e4-9c1e-e1f45751455f.png[/attachment]

**Comment by xillibit** [comment]
I have updated it, but for me the attach id is right here

**Comment by rich20** [comment]
- [x] Insert all - Succes
- [ ] Remove all - Failed (You can upload unlimited.) Example: Limit = 8

Upload 8 images then Remove all. Upload again 8 images and Insert all. After Submit you have 16 images in the message.

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Insert all - Success
- [x] Upload limit - Success 
- [ ] Remove all - Failed (The Button is inactive)

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
Attachments are removed only from the editor window. Here the result after click on submit:
bildschirmfoto vom 2015-07-12 23 14 29

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Insert all - Success
- [x] Upload limit - Success 
- [x] Remove all - Success

**Pull request merged**
