### PR TITLE
Categories view refactor

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue # . 
 
#### Summary of Changes 
So this is a big one (code wise):
* refactored filter
* refactored toggles on categories (published, locked, review, polls, anonymous) > These now all work again
* refactored sorting of order to use J5 scripts / logic
* new batch modal
 
#### Testing Instructions
please test filtering, sorting, batch function, delete button, etc.

### CODE REVIEW

**Comment by xillibit** [comment]
There are conflicts on this PR now because i have merged your other PR

**Comment by Ruud68** [comment]
When back in the office I will rebase this PR 👍

**Comment by Ruud68** [comment]
@xillibit  little 'fight' with the language file, but it is rebased now

**Comment by xillibit** [comment]
Thanks for all your works on refactoring the backend view

K6.3 can be installed actually on J4.4 and J5.0+ but with your changes i'am afraid that it will broken on J4.4, i haven't tested it on J4.4. If it's the case i will drop the suppport of J4.4 in K6.3 and keep it for K6.2.x

**Comment by xillibit** [comment]
When i set **Select Polls** to Yes in filter, i have : 
image

**Comment by Ruud68** [comment]
Let me check that tomorrow when back online, had to rebase this PR which was a bit messy so need to test if everything is still working.
Will follow up here

**Comment by Ruud68** [comment]
Hi, this error occured when sortorder was set but there was no categories to be displayed. Just fixed it.

**Pull request merged**
