### PR TITLE
 BBCodes for maps should be hardcoded #3690

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #3690 .

### CODE REVIEW

**Comment by rich20** [comment]
- [x] It works, however the code is written with uppercase letters

`[map type=TERRAIN zoom=2]Paris[/map]`

**Comment by 810** [comment]
Is it only on Crypsis?

**Comment by rich20** [comment]
Yes, these setting options are available only for Crypsis.

**Comment by xillibit** [comment]
I have set type value in lower case

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
