### PR TITLE
Ebay from cache #4014

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by 810** [comment]
Notice: Undefined property: stdClass::$Item in libraries/kunena/bbcode/bbcode.php on line 2763

Notice: Trying to get property of non-object in libraries/kunena/bbcode/bbcode.php on line 2763

Notice: Undefined property: stdClass::$Item in libraries/kunena/bbcode/bbcode.php on line 2764

Notice: Trying to get property of non-object in libraries/kunena/bbcode/bbcode.php on line 2764

Notice: Undefined property: stdClass::$Item in libraries/kunena/bbcode/bbcode.php on line 2765

Notice: Trying to get property of non-object in libraries/kunena/bbcode/bbcode.php on line 2765

Notice: Undefined property: stdClass::$Item in libraries/kunena/bbcode/bbcode.php on line 2767

Notice: Trying to get property of non-object in libraries/kunena/bbcode/bbcode.php on line 2767

**Comment by xillibit** [comment]
You need to clean cache before to try

**Comment by 810** [comment]
errors are still there:

ps you get the error on autolink ebay

**Comment by xillibit** [comment]
I have tried autolink and by using ebay bbocdes and i can't still see these issues

**Comment by 810** [comment]
see https://www.kunena.org/forum/k-4-0-installation-and-upgrade/137338-fatal-error-on-some-pages-after-4-0-11#175924

**Comment by 810** [comment]
ok seems to be working again.

**Pull request merged**
