### PR TITLE
[K4.0] Search: fix highlight search results #3090

### PR DESCRIPTION
**Pull request by 810**
- [x] Highlight search words: Blue Eagle
- [ ] Highlight search words: Crypsis

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Highlight search words: Blue Eagle - Success
- [ ] Highlight search words: Crypsis - Failed

**Comment by 810** [comment]
its also breaks the image result now

**Comment by 810** [comment]
Updated the code.

@xillibit could you check why the crypsis isn't loading the right file.

**Comment by xillibit** [comment]
Which file crypsis doesn't load correctly ?

**Comment by 810** [comment]
components/com_kunena/site/layout/search/results.php 

The code doesn't do anything. So he get the code from elsewhere

**Pull request closed without merging**
