### PR TITLE
Message "There are no topics to display" is not available in categories

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5299.

### CODE REVIEW

**Comment by sshcli** [comment]
This is how it looks now:
now

**Comment by sshcli** [comment]
The problem is solved, but...
Do you think you can move the message above the "New Topic" button ?

**Comment by sshcli** [comment]
I also think, the message should be removed if there are some folders in the category

folders
folders_blue_eagle

**Comment by xillibit** [comment]
> The problem is solved, but...
> Do you think you can move the message above the "New Topic" button ?

The message should be put into box to be more visible

> I also think, the message should be removed if there are some folders in the category

I will try to look to have the same behaviour than blue eagle

**Pull request merged**
