### PR TITLE
[K4.0] Crypsis: 3 party plugins don't showed on new topic #3095 (first try)

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by xillibit** [comment]
Should be working now

**Comment by 810** [comment]
not yet

**Comment by xillibit** [comment]
Why there is a big space in the middle ? Do-you have enabled plugins for kunena bbcode editor ?

**Comment by 810** [comment]
Yes, I have enabled my plugins. Also the bbcode for code is wrong

**Pull request merged**
