### PR TITLE
[K6.0] Get back the layout for mails like it was in K5.2 #9327

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #9327. 
 
#### Testing Instructions

### CODE REVIEW

**Comment by xillibit** [comment]
@rich20 : can-you test it to see if it have the same behaviour that K5.2 ?

**Comment by Leen29** [comment]
I'm trying but I think I made a mistake somewhere.
I got this message after I created a new topic in test forum.

Warning: Undefined variable $msg in /home/xxxxxxx/domains/xxxxxxx/public_html/libraries/kunena/src/Forum/Message/KunenaMessage.php on line 1680

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/xxxxxx/domains/xxxxxxxx/public_html/libraries/src/Mail/MailHelper.php on line 57
foutjeleen1

**Comment by xillibit** [comment]
> Warning: Undefined variable $msg in /home/xxxxxxx/domains/xxxxxxx/public_html/libraries/kunena/src/Forum/Message/KunenaMessage.php on line 1680

For this issue it's because it's missing the new files for layout, i had updated my PR yerstayday by adding these files : 

image

**Comment by Leen29** [comment]
Yes I already noticed that i use pkg_kunena_v6.0.4-DEV_2022-10-24.zip is that oke ?
but now I still have this error
[code]
  0 syntax error, unexpected token "catch"

call stack
# Function Location
1 () JROOT/libraries/kunena/src/Email/KunenaEmail.php:115
2 Composer\Autoload\includeFile() JROOT/libraries/vendor/composer/ClassLoader.php:428
3 Composer\Autoload\ClassLoader->loadClass() JROOT/libraries/src/Autoload/ClassLoader.php:59
4 Joomla\CMS\Autoload\ClassLoader->loadClass() JROOT/libraries/kunena/src/Forum/Message/KunenaMessage.php:576
5 Kunena\Forum\Libraries\Forum\Message\KunenaMessage->sendNotification() JROOT/components/com_kunena/src/Controllers/TopicController.php:968
6 Kunena\Forum\Site\Controllers\TopicController->post() JROOT/libraries/kunena/src/Controller/KunenaController.php:353
7 Kunena\Forum\Libraries\Controller\KunenaController->executeTask() JROOT/libraries/kunena/src/Controller/KunenaController.php:244
8 Kunena\Forum\Libraries\Controller\KunenaController->execute() JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:113
9 Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() JROOT/libraries/src/Component/ComponentHelper.php:355
10 Joomla\CMS\Component\ComponentHelper::renderComponent() JROOT/libraries/src/Application/SiteApplication.php:200
11 Joomla\CMS\Application\SiteApplication->dispatch() JROOT/libraries/src/Application/SiteApplication.php:241
12 Joomla\CMS\Application\SiteApplication->doExecute() JROOT/libraries/src/Application/CMSApplication.php:294
13 Joomla\CMS\Application\CMSApplication->execute() JROOT/includes/app.php:61
14 require_once() JROOT/index.php:32
[/code]

**Comment by xillibit** [comment]
Just replace completly the file /libraries/kunena/src/Email/KunenaEmail.php by the one which is in this PR

**Comment by Leen29** [comment]
After creating a new topic I keep getting these messages locally when I save topic.
so i'm still making a mistake somewhere.
[code]Warning: Undefined variable $msg in C:\Program\wamp64\www\newsmessages2022\libraries\kunena\src\Forum\Message\KunenaMessage.php on line 1680[/code] and also this message
[code]Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\Program\wamp64\www\newsmessages2022\libraries\src\Mail\MailHelper.php on line 57 [/code]

**Comment by xillibit** [comment]
~~Try with this nightly build with the changes : https://update.kunena.org/nightlybuilds/pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30.zip~~ Obsolete

**Comment by Leen29** [comment]
thanks
I'm testing pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30.zip after creating topic and sending I get a white screen.
(possibly because it's my .eu website but
will try different settings with joomla and kunena)
  but apparently the topic is being made.
and I receive an email from topic starter
  and also from a topic replay user
  An email will also be sent to the administrator email address
  
testmail1
mailtjes1

**Comment by xillibit** [comment]
~~Try with this new nighly build : https://update.kunena.org/nightlybuilds/pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30_v2.zip~~ Obsolete

**Comment by Leen29** [comment]
I also did another test with pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30.zip
on my pc with clean joomla and there also white screen after creating and sending new topic.

**Comment by Leen29** [comment]
sorry also with pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30_v2.zip after creating new topic and or reply send a blank image without error messages on the front.
Warnings can be seen in the E-mails
mailin
warninginmailin

**Comment by xillibit** [comment]
Try with this new nighly build : https://update.kunena.org/nightlybuilds/pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30_v3.zip

**Comment by Leen29** [comment]
remains the same also with the pkg_kunena_v6.0.4-DEV_PR9330_2022-10-30_v3.zip after creating and sending topic I get a blank white screen"/index.php?option=com_kunena&view=home&defaultmenu=2333&Itemid=2331" I refresh the browser with F5 then returns the screen with the message "Duplicate. Identical message has been ignored."
the emails also remain the same content with warning
I'm offline for a while today
aftherwhitescreenf5

**Comment by xillibit** [comment]
I have found that a die() was remaining in my code, my last commit remove it and fix in mail layout the undefined variable boardTtile

**Comment by rich20** [comment]
It seems, this fix solved also this bug: https://github.com/Kunena/Kunena-Forum/issues/9220

**Comment by Leen29** [comment]
Yes, now it seems to work fine.
Emails are also coming in 
yesokenow
yesokemailintruus
inhoudtest5truus

**Pull request merged**
