### PR TITLE
Crypsis: Target topic does not change to another category #3517

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
also do crypsisb3

**Comment by rich20** [comment]
-  [ ] Failed - no reaction

> also do crypsisb3

it's the same

**Comment by 810** [comment]
Is the fix working rich. because you selected the box. but you entered Failed

Also is "it's the same" working or not

**Comment by rich20** [comment]
Sorry, I had automatically inserted the x. My mistake and I have it changed. It's the same, both does not work.

**Comment by xillibit** [comment]
Try now

**Comment by 810** [comment]
Almost, you need to open the target selectbox 2x to see the right categories

**Comment by rich20** [comment]
- [x] Success

**Comment by xillibit** [comment]
That's the same behaviour that on blue eagle

**Comment by 810** [comment]
ok, its the delay, can we improve that more, or is it to hard to find where the long delay is.

**Comment by xillibit** [comment]
It does an ajax request so it's maybe the reason why you have a dalay

**Comment by 810** [comment]
ok, I merge this one for now.

**Pull request merged**
