### PR TITLE
Fix: refactored modals not working correct

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue # https://github.com/Kunena/Kunena-Forum/issues/9646. 
 
#### Summary of Changes 
the following refactored to 4.4 modals where not sumbitting data / form correct:

- logs > clean
- users > moderators
- users - subscribecategories
- categories > batchmove

#### Testing Instructions
test not only if modals work (they actually show), but if submitting / processing also works

### CODE REVIEW

**Comment by xillibit** [comment]
> * users > moderators
> 
> * users - subscribecategories

Tested on Joomla! 4.4, when submit the modal it does nothing

> * categories > batchmove

image

**Comment by Ruud68** [comment]
@xillibit let me check that tomorrow

**Comment by Ruud68** [comment]
Ok, I'm sure I tested all (except the category batch one): go figure.
Same issue as with some other controller method names: batchCategories method is the same as var in view / model. Somehow PHP / Joomla doesn't like this any more.
So renamed the method to all lowercase and now it works.

presuming this was the only modal not working, this should now be okay.

Updated this PR with new commit

**Comment by Ruud68** [comment]
Ok, just did a test and now the controller method is called okay. But now it is saying that I forgot to select a target category.

Turnout that the controller is getting the selected category from a field on the form that doesn't exist (and also didn't exist in K6.2 so this never worked?).
Anyway, did a last small change (in this PR) and should be working now.
Can you test @xillibit ?

**Comment by xillibit** [comment]
There was two options in the categories batch one have never worked, so i have removed part in the template

**Pull request merged**
