### PR TITLE
Add token on timeselect for topics and messages #5737

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5737 .

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] It shows no topics at the menu items Recent Topcs, My Topics and No Replies

**Comment by rich20** [comment]
Addendum: If you switch two times the time period, it shows the topics correct. But you must do this every time if you choose another menu item.

**Comment by 810** [comment]
@xillibit could you check if this is ok.

**Comment by xillibit** [comment]
Just tested seems to be better

**Pull request merged**
