### PR TITLE
[K5.2] Translation datepicker doesn't work #6527

### LINKED ISSUE #6527: Translation datepicker doesn't work
See desc

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #6527. 
 
Close #6527

#### Testing Instructions

### CODE REVIEW

**Comment by xillibit** [comment]
@sshcli or @rich20 : can-you test it please ?

**Comment by sshcli** [comment]
Test Results = Fail
The translated word is working, but when you try to select a date it shows this:
error

**Comment by rich20** [comment]
For me it works. I've tested with 5 different languages. The bootstrap datepicker files will be correct loaded from the new path /media...

**Comment by xillibit** [comment]
> Test Results = Fail
> The translated word is working, but when you try to select a date it shows this:

Try to enable debug language from Joomla! and check if the chains are translated in our language

**Comment by sshcli** [comment]
> Try to enable debug language from Joomla! and check if the chains are translated in our language

I have enabled the Language debug in Joomla
These are the results:

good

bad

**Comment by rich20** [comment]
> Test results = Fail
> I see this error in console and can't pick a date:
> 
> ```
> GET https://example.com/components/com_kunena/template/crypsis/assets/bootstrap.datepicker.css net::ERR_ABORTED 404
> 425-j352:42 GET https://example.com/components/com_kunena/template/crypsis/assets/bootstrap.datepicker.js net::ERR_ABORTED 404
> 425-j352:43 GET https://example.com/components/com_kunena/template/crypsis/assets/bootstrap-datepicker.lang.kunena.js net::ERR_ABORTED 404
> jquery-migrate.min.js?b3d3b98991339cab484c4d96fd3b4286:2 JQMIGRATE: Migrate is installed, version 1.4.1
> 425-j352:42 GET https://example.com/components/com_kunena/template/crypsis/assets/bootstrap.datepicker.js net::ERR_ABORTED 404
> 425-j352:43 GET https://example.com/components/com_kunena/template/crypsis/assets/bootstrap-datepicker.lang.kunena.js net::ERR_ABORTED 404
> ```

That's the old paths. The files are now in /media/kunena/core...
Maybe its the cache?

**Comment by xillibit** [comment]
Yes it seems to be the cache

@sshcli : i'am not able to reproduce your issue 

image

**Comment by sshcli** [comment]
> That's the old paths. The files are now in /media/kunena/core...
> Maybe its the cache?

No, that problem has been solved, that was an outdated build.
That's why I have deleted the comment, because with the new build, the error is gone.

**Comment by rich20** [comment]
Ok, so we can mark it as solved.
- [x] Success

**Pull request merged**
