### PR TITLE
Metadescriptions not taken in Kunena menu for Joomla! menu manager

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
@rich20 could you test it again with k3.0.8 and J3.4.1

**Comment by rich20** [comment]
In principle it's the same as earlier.
> - [x] Menu Item Category List (Index) - Success
- [x] Menu Item Recent Topics - Success
- [x] Menu Item Search Topics - Success
- [x] Menu Item Show Category (Single Categories) - Sucess
- [x] Menu Item Custom Content - Success
- [ ] Menu Item Recent Posts - Failed

**Comment by 810** [comment]
I think we can close this pr, because I added all metas on each view

**Comment by 810** [comment]
I'm closing this one.

New PR: https://github.com/Kunena/Kunena-Forum/pull/3528

**Pull request closed without merging**
