### PR TITLE
When Direct Component Access and Protect Attachments is active, Images

### PR DESCRIPTION
**Pull request by xillibit**
will not appear in the backend #3635

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] Failed

**Comment by xillibit** [comment]
What is the link that you have of thumb image with the fix ?

**Comment by 810** [comment]
http://www.rich20.at/test-5-487329874//test-5-487329874/index.php?option=com_kunena&view=attachment&id=28&thumb=1&format=raw

**Comment by xillibit** [comment]
With this fix the link on thumbs for protected attachments are like that : /joomla3.3.6/index.php?option=com_kunena&view=attachment&id=1&thumb=1&format=raw

**Comment by 810** [comment]
i miss the administrator dir

**Comment by rich20** [comment]
- [ ] Does not work without SEO (no thumbs and wrong address)

**Comment by xillibit** [comment]
I hadn't checked without SEO, i will check with that

**Comment by 810** [comment]
@xillibit could you merge my pr

**Comment by xillibit** [comment]
> @xillibit could you merge my pr

Do-i still need to merge your PR ?

**Comment by 810** [comment]
yes. Could you test it also

**Comment by xillibit** [comment]
When you set Direct Component Access on No, it check the menu active item and if it doesn't find or find the menu item is wrong it display a 404 page. So in this case i don't know how to display attachments in backend.

**Comment by 810** [comment]
then load the icon

`echo '<i class="'. $icon .' icon-big"></i>';`

**Comment by rich20** [comment]
> then load the icon
> 
> `echo '<i class="'. $icon .' icon-big"></i>';`

That solves not the problem with the wrong addresses.

> With this fix the link on thumbs for protected attachments are like that : /joomla3.3.6/index.php?option=com_kunena&view=attachment&id=1&thumb=1&format=raw

format=raw&itemid=xxxx
If the itemid is added at the end of the address it works for both (link to images and it shows thumbs). It works with and without SEO

**Comment by xillibit** [comment]
If i add the &itemid=xxxx at the of url it doesn't work better

**Comment by 810** [comment]
maybe we should disable link on the backend on that, when its protected and sef is turned off.

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Direct Component = No - it shows only icons without link
- [x] Direct Component = Yes - the images will displayed correct
- [x] Direct Component = Yes - the attachments can be called using the browser
- [ ] It remain the problem with the double address such as 

website/joomla-test/joomla-test/index.php?option=com_kunena&view=attachment&id=3&format=raw

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Direct Component = No - it shows only icons without link
- [x] Direct Component = Yes - the images will displayed correct
- [x] Direct Component = Yes - the attachments can be called using the browser
- [x] It remain the problem with the double address

**Pull request merged**
