### PR TITLE
[3.1] Rss: Hide message if teaser is enabled

### PR DESCRIPTION
**Pull request by 810**
- by posts
- by recent messages

### CODE REVIEW

**Comment by rich20** [comment]
- [x] By Posts - Success
- [x] By Recent Messages - Success

**Comment by xillibit** [comment]
Works only with blue eagle with two RSS settings, with crypsis it works only for first message of RSS feed

**Comment by sozzled** [comment]
When you think about it, if a site owner enables RSS feeds but effectively says, "here's the RSS feed but, no, I'm not showing anyone who is not logged in what content has been added", this actually contradicts the whole point of allowing RSS feeds, doesn't it?

Sure, it might be possible to restrict the content in RSS messages but, really, when you think about it, if a site owner "teased" everything then the RSS would have nothing to report.  The simplest way to overcome the "problem" is to disable RSS feeds.

I think that allowing RSS feeds on a site that has K 3.1 where the teaser feature is enabled will result in more questions (and possible complaints) being raised that it will benefit users by "fixing" the source code in the way that was suggested by Jelle.

Just my opinion.

**Comment by rich20** [comment]
The rss-feed makes sense if you use "Feed type By Topic". It shows only the first message from a topic (the same as with teaser in the forum).

**Comment by sozzled** [comment]
It's just my opinion, of course, but I still feel that you have not thought through the ramifications of allowing RSS feeds but, effectlvely, disabling the content.  Remembering that the purpose of teasers is to "encourage" people to login to the forum to use it, RSS feeds (because there is no "login") is a back-door way of accessing the forum.

The problem could be addressed with a techical solution (as proposed by Jelle) but, in practice, having RSS feeds and teasers is somewhat contractory and defeats the purposes of both.

**Pull request merged**
