### PR TITLE
 [K4.0.5] Max Links in message does not work. You can add unlimited

### PR DESCRIPTION
**Pull request by xillibit**
#3390

### CODE REVIEW

**Comment by 810** [comment]
not working,
can still add "www.test.com" unlimited

**Comment by xillibit** [comment]
You shouldn't be an admin or moderator

**Comment by 810** [comment]
ok worked,
option = 6
but when I add 5x "www.test.com" and add 2 youtube. the topic is posted. but I see only 3x "www.test.com" and 2x youtube vids.

When edit, I see all the links

**Comment by rich20** [comment]
If you edit a message, you can add again the limit.

**Comment by rich20** [comment]
Correction, if you edit, you can add unlimited.

**Comment by xillibit** [comment]
try now

**Comment by 810** [comment]
- [x] normal link ok
- [x] edit normal links
- [ ] Links with youtube 5x links 2x youtube
- [ ] edit Links with youtube 5x links 2x youtube

**Comment by rich20** [comment]
- [x] normal link ok
- [x] edit normal links
- [x] image links
- [x] edit image links
- [ ] youtube links are unlimited

**Comment by xillibit** [comment]
try now

**Comment by 810** [comment]
- [x] normal links
- [ ] edit links
- [ ] links + youtube unlimited

**Comment by 810** [comment]
if we can go back to the last commit, its fine. I never see spam with multiple youtube vids.

So is images and links is working, then we can merge it.

**Comment by xillibit** [comment]
Reverted to last commit

**Comment by rich20** [comment]
Yes, now is the same as before.
- [x] normal link ok
- [x] edit normal links
- [x] image links
- [x] edit image links
- [ ] youtube links are unlimited

**Pull request merged**
