### PR TITLE
Ban users in the frontend is not possible #6596

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #6596 . 
 
#### Testing Instructions

### CODE REVIEW

**Comment by rich20** [comment]
-  [x] Success

**Comment by rich20** [comment]
hm.. I see now, ban from the forum with end time does not work. Ban from the page with end time works but can see it only tomorrow, whether the ban will automatically removed.

**Comment by xillibit** [comment]
> hm.. I see now, ban from the forum with end time does not work. 

Why do-you mean by it doesn't work ?

**Comment by rich20** [comment]
If you ban an user only from the Forum (not from the site) and you set a time where the ban ended, then the user should not have write access before the ban ended. But the user remain a normal user without ban and can nevertheless write posts.

**Pull request closed without merging**
