### PR TITLE
Refactored broken stats

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue # . 
 
#### Summary of Changes 
Fixed the stats view
created a menu item for it (Forum Statistics)
added it as a tile in the cpanel (in the place of the statistics)

note: changed language files!
 
#### Testing Instructions
not much to test other then if it shows the correct forum statistics / user statistics

### CODE REVIEW

**Comment by Ruud68** [comment]
I think this is the final 'ListModel / View' back-end change for 6.3
next would be the FormModel / view refactoring, but that is also a lot of work and I think that this will be to muc for 6.3, so 6.4 maybe?

**Comment by xillibit** [comment]
For the big changes you can wait the branch K6.4, i will create this branch after the release of K6.3.x in stable.

**Comment by xillibit** [comment]
Later in the day when the beta1 of Joomla! 5.1 will be released i will make the release of beta1 of K6.3. The branch K6.2 because is the last one to support Joomla! 4.4 needs to be maintened untill at last october 2024 because it's the end of bugfix

**Comment by Ruud68** [comment]
Did you test 6.3 on J4.4? To see if it works?
If there are any J5 specific changes in my PR's maybe I can rewrite them to be J4.4 compatible.

Do not currently have a J4 test site with Kunena on it (all my sites already migrated to J5)

**Comment by xillibit** [comment]
Yes i had tested K6.3 on J!4.4 when you had started the refactoring to some view, there was an error about PopupButton class ,not found

**Comment by Ruud68** [comment]
Ok, if that is the only one I will do a PR this afternoon to replace that with J4 equivalent

**Comment by Ruud68** [comment]
@xillibit https://github.com/Kunena/Kunena-Forum/pull/9645

**Comment by xillibit** [comment]
I will test in the evening your two PR now i don't have the means to test it

**Comment by xillibit** [comment]
It's intended that you have the filters like it was : 
image

**Comment by Ruud68** [comment]
That is the deprecated view statistics, that is removed from the menu. This is the &view=stats
it is set in the sidemenu and on the cpanel tile (Forum Statistics)

**Comment by Ruud68** [comment]
image

**Comment by xillibit** [comment]
The menus aren't updated when i do a checkot i have couple of issues : 
image

**Comment by Ruud68** [comment]
that's the old stats view, I think that there was an issues with the checkout files?

just did a quick check on the commited files in this PR and these are the correct / refactored ones. So must be an issue on your side

**Comment by xillibit** [comment]
i have uninstalled Kunena and done a proprer install it's better now : 
image

**Comment by Ruud68** [comment]
That is the correct one

**Pull request merged**
