### PR TITLE
Announcements will not published with selected date #3459

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by rich20** [comment]
Error

Unknown column 'publish_down' in 'field list' SQL=INSERT INTO `prefix_kunena_announcement` (`id`,`title`,`created_by`,`sdescription`,`description`,`created`,`publish_up`,`publish_down`,`published`,`showdate`) VALUES ('0','Test Announcement','355','short text short text short text','','2016-03-09 21:41:58','','','1','1')

**Comment by 810** [comment]
clean install ? or update

**Comment by 810** [comment]
check that all alpha4 version are deleted in version table. Then install again. I think you tried the same database for voting. so try again

**Comment by rich20** [comment]
Is with a clean installation the same. You can't create a announcement.

**Comment by rich20** [comment]
- [x] Create announcements on a clean installation 
- [ ] Create announcements on a updated forum - error Unknown column... (see above)
- [ ] Announcement will be published immediately (no matter which date is selected)
- [ ] By default all date fields are empty

**Pull request merged**
