### PR TITLE
 Crypsis : implement blue imp jquery uploader to handle attachments #2641

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
### New topic
- [x] Make upload of new attachments working
- [x] Take care of Kunena configuration to limit attachments number
- [x]  Insert image in messages
- [x]  Load attachments already uploaded previously by user when it edit message
- [x]  Let user remove attachments already uploaded on filesystem
- [x]  Add JText strings in javascript to be able to translations
- [x]  Use minimal number of js files from plugins
- [ ]  Add a button to upload all files present in the message form
- [x]  Add dropzone with text to describe to drag&drop files and still keeping usage of buttons (drag&drop works by default)
- [x] Image uploaded opened in a lightbox
- [x]  Add label with max attachments + size

### Edit
- [x] Insert
- [x] Remove existing attachments - Success
- [x] Add images

**Comment by rich20** [comment]
> ### New topic

>  - [x]  Make upload of new attachments working
 - [x]     Take care of Kunena configuration to limit attachments number
 - [x]     Insert image in messages
 - [x]     Load attachments already uploaded previously by user when it edit message
 - [x]     Let user remove attachments already uploaded on filesystem
 - [x]     Add JText strings in javascript to be able to translations
 - [x]     Add a button to upload all files present in the message form
 - [x]     Add dropzone with text to describe to drag&drop files and still keeping usage of buttons (drag&drop works by default)
 - [x]     Image uploaded opened in a lightbox
 - [x]    Add label with max attachments + size

> ### Edit

>  - [x]  Insert
 - [x]    Remove existing attachments - Success
 - [x]    Add images

Use minimal number of js files from plugins (Here, I don't know what is it.)

**Comment by rich20** [comment]
- [x] Autoupload - Succes
- [ ] Add file > Remove > Add file again - Failed (you can not see the attachments)
- [ ] Add filet and remove - Failed (you must edit the message then you can do it)

**Comment by xillibit** [comment]
Updated

**Comment by rich20** [comment]
- [x] Autoupload - Success
- [x] Remove progress bar - Success
- [x] Add file > Remove > Add file again - Success
- [x] Add file and remove - Success

It works all now

**Comment by 810** [comment]
+1 Need one more test. then we can merge this, I will fix the css issue after the merge

**Comment by rich20** [comment]
> ### New topic

>  - [x]  Make upload of new attachments working
 - [x]     Insert image in messages
 - [x]     Load attachments already uploaded previously by user when it edit message
 - [x]     Let user remove attachments already uploaded on filesystem
 - [x]     Add JText strings in javascript to be able to translations
 - [x]     Add dropzone with text to describe to drag&drop files and still keeping usage of buttons (drag&drop works by default)
 - [x]     Image uploaded opened in a lightbox
 - [x]    Add label with max attachments + size
 - [x]    Add file > Remove > Add file again - Success
 - [x]    Add file and remove - Success

 - [ ]     No message if the limit attachments number is reached
 - [ ]     Limit attachments works only with the Add File button. With drag&drop you can upload more.
 - [ ]     Uploaded attachment with more than maximum file size cannot to be removed from the editor. Remove File does not work.


> ### Edit

>  - [x]  Insert
 - [x]    Remove existing attachments - Success
 - [x]    Add images

**Comment by xillibit** [comment]
Thanks rich for the updated report i will look later to fix these items

**Comment by xillibit** [comment]
I have updated it now it show message when you have reach the limit of attachments number

**Comment by rich20** [comment]
- [x] No message if the limit attachments number is reached

**Comment by 810** [comment]
- [ ] Limit attachments works only with the Add File button. With drag&drop you can upload more.
- [ ] Uploaded attachment with more than maximum file size cannot to be removed from the editor. Remove File does not work.
- [ ] Uploaded attachment with wrong extension cannot to be removed from the editor. Remove File does not work.

**Comment by xillibit** [comment]
With drag&drop if you reach limit it display too the alert, nobody see that ?

**Comment by 810** [comment]
No, error message, the images are uploaded

**Comment by rich20** [comment]
> With drag&drop if you reach limit it display too the alert, nobody see that ?

You can see it, if the limit (or more) has been reached and you want again drag&drop. 
The same with edit. If the limit (or more) has been reached and you want again drag&drop, then you see the alert.

**Comment by xillibit** [comment]
You should be able to remove items if wrong extension

**Comment by 810** [comment]
yes, the remove works now. Can you remove the number 400 on the error, just the text

**Comment by xillibit** [comment]
I have a weird issue, the file size send by script is wrong before it worked well :disappointed: 

I will display the error message without the 400

With drag&drop like add button, if the limit in config is set to 4 attachments then i can add 4 attachments but if i try to put a fifth attachment i can see the alert

**Comment by 810** [comment]
ok, try click on button. Go to pictures, select 6 images. click on upload. Then you will see, that he isn't checking the limit.

**Comment by rich20** [comment]
> With drag&drop like add button, if the limit in config is set to 4 attachments then i can add 4 attachments but if i try to put a fifth attachment i can see the alert

Yes, this is correct, I had written it earlier. 
>You can see it, if the limit (or more) has been reached and you want again drag&drop.

But as long as the limit has not been reached, you can upload more.

**Comment by xillibit** [comment]
I have updated to improve check of uploaded files when you use upload button or when you drop files.

**Comment by 810** [comment]
You can't remove a image, and add a new image, if the number is reached

**Comment by xillibit** [comment]
Should be ok now

**Comment by 810** [comment]
same

**Comment by xillibit** [comment]
And now ?

**Comment by 810** [comment]
check is ok now, but the old one is still uploaded, he is deleted, but still on the attachments
my settings is max 6 , but i see 7 now

**Comment by rich20** [comment]
Via edit Add File button you can again upload up to the limit.
Example: Upload the maximum attachments and submit. Now edit the message and you can upload again the maximum attachments, and so on..

**Comment by xillibit** [comment]
@810 : i have fixed that in my last commit
@rich20 : now it should be count the uploaded attachments when you edit

**Comment by 810** [comment]
yes fixed

**Comment by rich20** [comment]
- [x] Count the uploaded attachments when you edit - Success

A general problem is still there. The number of the limit should be displayed.
If a user drag to many images at the same time then will nothing uploaded. It shows only "You have reached the maximum number of files allowed". He must find the limit itself.

**Comment by xillibit** [comment]
I have updated it to show the max number of files allowed in config

**Comment by 810** [comment]
good, only the size and type left

**Comment by xillibit** [comment]
Missing for the file size because if you try to upload file with not allowed extension you can the alert message

**Comment by 810** [comment]
could you automatic remove item on "400 The file size (1397811) exceeds the maximum set by the administrator."

also change 400 to the end, and add "error" before 400

**Comment by xillibit** [comment]
I have removed the error code (400 in your message) from the error message displayed

**Comment by 810** [comment]
could you also change (1397811) to mb, and add the mb text.

We should move everywhere from kb to mb.

**Comment by xillibit** [comment]
When l try to upload files that exceed the maximum weight it juste
uploaded, it's weird that you have thé alert

**Comment by 810** [comment]
images are uploaded, because the size will be resized. But files you get the error

**Comment by rich20** [comment]
Maximum File Size: and Maximum Image File Size: needed also translation

**Comment by xillibit** [comment]
You can check now i have modified to have MB in all places

**Comment by rich20** [comment]
Theese both sentences needed also translation.
Maximum File Size:
Maximum Image File Size:

**Comment by xillibit** [comment]
that's have already a translation into /components/com_kunena/site/template/crypsis/language/en-GB/en-GB.kunena_tmpl_crypsis.ini : 

```ini
COM_KUNENA_UPLOAD_MAX_FILES_WEIGHT="Maximum File Size"
COM_KUNENA_UPLOAD_MAX_IMAGES_WEIGHT="Maximum Image File Size"
```

**Comment by rich20** [comment]
Ok, but I've no idea where does it comes.
bildschirmfoto vom 2015-02-04 19 38 53

**Comment by 810** [comment]
looks good now, could you change the size to just 1 decimal. so like 1.1MB

Also could you redo the pr

**Comment by xillibit** [comment]
I will change with just one deciaml, this PR should be just updated i think

**Comment by xillibit** [comment]
@rich20 : all is ok for you ?

**Comment by rich20** [comment]
In principle works all, only the problem with "Protect Attachments" still exists.
### New Topic
- [ ] Protect Attachments : Only Images in messages will opened in a lightbox

### Edit
- [ ] Protect Attachments : You cannot see the images in the editor (the url can not be loaded)

**Comment by xillibit** [comment]
For new topic it's an already known issue : https://github.com/Kunena/Kunena-Forum/issues/2313, for edit i need to find a way to fix it for now i don't found a way

**Pull request merged**
