### PR TITLE
Load category template text by ajax

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by sshcli** [comment]
Test results....
The modal to confirm changes is showing up = OK ✔
The "Close" button in modal is working = OK ✔
The "Replace content" button in modal is working = Fail ❌
The "Replace content and keep existing" button in modal is working = Fail ❌
Every text in modal windows has its own language string = Fail ❌

**Comment by xillibit** [comment]
Try now

**Comment by 810** [comment]
when i click on "replace content" i get old cat text +new cat text

**Comment by sshcli** [comment]
> when i click on "replace content" i get old cat text +new cat text

I was having the same results as you, but that was was before the last change made by @xillibit 

Now, when I press the "Replace content" or "Replace content and keep existing" button, the text area is cleared and you need to click the category dropdown to insert the template again.

**Pull request merged**
