### PR TITLE
Refactor Back-end Views; Users

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue # . 
 
#### Summary of Changes
Refactored Users view into J5 compliant view:

- Toolbar changed
- Filter (search) working
- Table sorting working
- Columns toggle (display / hide)
- cleanup rows
- fixed signature, enabled, banned 'buttons' on user row
- new modals for moderators and subscriptions
- new language strings (are they in the correct file?)
- removed rank filtering as that never worked as far as I know (ranks are assigned dynamically where filter works on database)

 
#### Testing Instructions
I have done some basic / simple tests, but basically everything should be tested with one /multiple users selected.
Also test if front-end is still working as the UsersModel has changed and I am not sure if things I refactored / deleted are used in other areas of the forum other then the back-end)/

If this PR is okay, we can use it as a 'baseline' for the other views as well.

Let me know what you think!

### CODE REVIEW

**Comment by Gindi50** [comment]
Kunena 6.3.0BETA1
When I edit the user profile, the text "COM_KUNENA_MYPROFILE_bsky_app" is displayed under the text "Reddit" in the profile information.

**Comment by Gindi50** [comment]
Kunena 6.3.0-BETA1 with new filter_users.xml
When I click on Kunena users in the backend, everything in the Kunena code is displayed in the sort field for "Name ascending". (COM_KUNENA_FILTER_FIELD_USERNAME_ASC).

**Comment by Ruud68** [comment]
Hi @Gindi50 thanks for testing, you should also apply changes to language files as these are new language strings net yet in beta1
In the PR I did you can see what language files and what is added

**Comment by Gindi50** [comment]
There is a typing error in the file "libraries/kunena/src/User/KunenaUser.php".
In row 2237 it says: 
'bsky_app' => ['url' => 'hhttps://bsky.app/profile/##VALUE##.bsky.social', 'title' => Text::_('COM_KUNENA_MYPROFILE_BLUESKY_SOCIAL'), 'nourl' => '0'],
With https there is one "h" too many.

**Comment by Ruud68** [comment]
Hi, that file.is.not part ofy refactor PR.
I'll go online later this afternoon and will do.a.quick fix for this in another PR.
Thanks for reporting and investigating!

**Comment by Ruud68** [comment]
Hi,
also had some time to refactor the Attachments view into J5 compatible view

**Comment by Ruud68** [comment]
Hi, also refactored the Ranks view + re added some removed Users methods (made them deprecated instead to avoid issues for other developers using them in their code)

**Pull request merged**
