### PR TITLE
Restore Unapproved Topics not working as expected #3846

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #3846.

### CODE REVIEW

**Comment by rich20** [comment]
- [x] If you move the complete topic to the trash and restore it, pending messages remain pending messages
- [ ] If you delete only a single pending message - after restore the message is approved

**Comment by rich20** [comment]
But I mean, if you delete a single message, you have also checked the message content

**Comment by xillibit** [comment]
For a single message it's useless because the unapproved state is lost when you delete the message

**Comment by rich20** [comment]
- [x] If you move the complete topic to the trash and restore it, pending messages remain pending messages
- [ ] If you delete only single pending messages (see image) - after restore the messages are approved
  bildschirmfoto vom 2016-04-27 23 23 54

**Pull request merged**
