### PR TITLE
Twitter and ebay widgets prevent to add the post because there are a lot of links

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
you should do it twice.  create and reply same file

**Comment by xillibit** [comment]
try now

**Comment by 810** [comment]
code works:

- [x] Crypsis
- [ ] Blue eagle 
- [ ] Crypsis b3

You need also add it to other templates

**Comment by xillibit** [comment]
Updated

**Comment by 810** [comment]
- [x] Tweets
- [x] Ebay
- [ ] Max links
I get "You have to many links in your message, please decrease it!"
but the message is posted

**Comment by xillibit** [comment]
> Fatal Error: Call to a member function authorise() on a non-object in components/com_kunena/controllers/topic.php on line 877
> 
> I get this with the new count fix.
> 
> if (!$topic->authorise('approve') && $countlink >=$this->config->max_links +1) {

try now

**Comment by 810** [comment]
with https://github.com/Kunena/Kunena-Forum/pull/3182/files
I get still the error

**Comment by xillibit** [comment]
try now

**Comment by 810** [comment]
Fatal is fixed.

But the max links isn't working yet, I get the error but he is posting the message

**Comment by xillibit** [comment]
Try now

**Comment by 810** [comment]
not working, should be 
````
if (!$topic->authorise('approve') && $countlink >=$this->config->max_links +1)  {
				$this->app->enqueueMessage ( JText::_('COM_KUNENA_TOPIC_SPAM_LINK_PROTECTION') , 'error' );
				return false;
			}
````

**Comment by xillibit** [comment]
I have tested it and it works, it already checking that in the method

**Comment by 810** [comment]
please try with guest user.

Now its always getting the error message, and can't post a reply.

**Comment by xillibit** [comment]
I had reversed the return value

**Comment by 810** [comment]
now it worked

**Pull request merged**
