### PR TITLE
5 star Rating #981

### PR DESCRIPTION
**Pull request by 810**
Not finished yet.

### CODE REVIEW

**Comment by xillibit** [comment]
You have just updated on this PR the Sven branch against develop ?

**Comment by 810** [comment]
I started from K5.0 then copied the code from sven's branch. 

When i did it on develop its was working, but on K5.0 its not working anymore.

**Comment by xillibit** [comment]
I'am looking to it actually to try to make it working

**Comment by xillibit** [comment]
Replaced by #3735

**Pull request closed without merging**
