### PR TITLE
Attachment preview goes wrong in some cases #5390

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5390 .

### CODE REVIEW

**Comment by rich20** [comment]
The problem is another. If you insert a new image in a message, it will no displayed in the preview. The image can't be displayed, before it is uploaded. But the upload occurs during submit the message.
Therefore you see on edit the previously uploaded images but not the new inserted images.

g4690

**Comment by xillibit** [comment]
I have tried by adding an new attachment image, i haven't checked by adding an image which isn't an attachment

**Comment by rich20** [comment]
When you add a image, the image is only registered in the database. Therefore you have no preview. It will then be uploaded if you click on Submit.  Afterwards the preview works for this image.

**Comment by xillibit** [comment]
In fact it's the reverse, when you submit your message the attachment is saved in database

**Comment by rich20** [comment]
You can test it.
1. Click on reply
2. Add a attachment
3. Click Cancel or Remove Attachment (or do nothing)
4. Check the database or go in backend to "Tools -> Diagnostics"
The attachment is now listed as orphaned

**Comment by xillibit** [comment]
Try now it should works

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
