### PR TITLE
Remove hard coding from bbcode editor

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue https://github.com/Kunena/Kunena-Forum/issues/6122

### CODE REVIEW

**Comment by 810** [comment]
1) the js is created by \libraries\kunena\bbcode\editor.php
2) check also crypsisb3

**Comment by sshcli** [comment]
> check also crypsisb3

Done

**Comment by rich20** [comment]
- [x] Success

Only one question: Why is added this one string "Text::script('COM_KUNENA_EDITOR_UNORDERED_LIST');"? We have already the translated string "Text::script('COM_KUNENA_EDITOR_ULIST'); for the same option.   The string "Text::script('COM_KUNENA_EDITOR_UNORDERED_LIST');" is unneeded, I think.
https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/template/crypsis/layouts/topic/edit/default.php#L35

**Comment by sshcli** [comment]
> Why is added this one string "Text::script('COM_KUNENA_EDITOR_UNORDERED_LIST');"? 

Didn't notice. Has been removed now

**Comment by rich20** [comment]
> Didn't notice.

Not your mistake. I've noticed today that this string is unneeded. It would be a orphaned string without function.

**Pull request merged**
