### PR TITLE
fix svg size of sub category icons when custom class is used on paren…

### PR DESCRIPTION
**Pull request by Ruud68**
…t directory

Pull Request for Issue #9424 . 
 
#### Summary of Changes 
removed 'conflicting' scss

#### Testing Instructions
install PR
visit form (make sure css is regenerated).
test all views and see if icons are still correct (when used in combination with 'category-' class (e.g. category-green)

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] <strike>Success</strike>

**Comment by rich20** [comment]
Sorry, it was a mistake by me.
It shows on Recent Topics and Recent Posts page now also the mini symbol
.
Bildschirmfoto vom 2022-12-17 12-49-29

**Comment by Ruud68** [comment]
Hi,
~~so what is happening here is that by default the class for this row is "category"~~

~~class category is used to style the row.~~

~~Now by setting "-green" the class is changed to "category-green". This is expected but as category-green is not styled the same as category things are going wrong (like the styling of the svg icon).~~

~~My proposal would be to always set category as class and add category-green additionally when -green is configured.~~

~~but before making this change we can test this by configuring the category class not to "-green" but to "[space]category-green"
where [space] = a space :)~~
~~so now the class will become "category category-green"~~

~~@rich20 can you test if this works? It is used in views:~~

**Comment by Ruud68** [comment]
sorry, never mind the test. did a change to the PR.
Can you test that?

**Comment by rich20** [comment]
- [x] Now everything is correct

**Pull request merged**
