### PR TITLE
It lacks the delete button in K 5.0.2 #4633

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #4633 .

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Use Can Delete Own Post = Always
- [x] User Can Delete Own Post = When no Replies
- [x] User Can Delete Own Post = Never
- [ ] User Can Delete Own Post = All, except first message of topic - Failed (User can nothing delete)

**Comment by xillibit** [comment]
> User Can Delete Own Post = All, except first message of topic - Failed (User can nothing delete)

For me it works like it should, i can't delete the first message but the second one i can delete

**Comment by 810** [comment]
yes, for me its ok also, maybe rich is a moderator and can see the delete button

**Comment by rich20** [comment]
Yes, it works, maybe it was the cache.

**Pull request merged**
