### PR TITLE
Category rss is now by topic

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue https://github.com/Kunena/Kunena-Forum/issues/5475

#### Summary of Changes
Before this change the rss for categories where showing the last post. (aka reply)
After this change the rss for categories are showing the first post. (aka topic) 

Note:
RSS for categories doesn't have the option to switch between RSS Feed type (Post,Topic, Recent Topics). 
A new PR should be made in order to add support for this option.

### CODE REVIEW

**Comment by sshcli** [comment]
@rich20 @810 @xillibit  Please feel free to improve these changes if needed.

**Comment by rich20** [comment]
Please check this patch again. Opera can't see the news from the subcategories, when is only subscribed the main category. Maybe is included a command, which Opera not know.
The feed shows the first message and the links go to the first message now with all browsers (Chromum, Opera and Firefox). 
Without this patch you see the currently message and also the link goes to the currently message.

**Comment by sshcli** [comment]
> Opera can't see the news from the subcategories, when is only subscribed the main category. 

In my test with Opera, It shows the subcategory always (With and without this patch).
**Without Patch**
withoutpr

**With Patch**
withpr



> The feed shows the first message and the links go to the first message now with all browsers (Chromum, Opera and Firefox).
Without this patch you see the currently message and also the link goes to the currently message.

That's right, the purpose of this pr is to show the topics instead of replies.

**Comment by rich20** [comment]
> In my test with Opera, It shows the subcategory always (With and without this patch).

Maybe the Linux Opera is not identical with Windows Opera. But the ordering of topics is without this patch correctly also with my Opera browser.

> The feed shows the first message and the links go to the first message now with all browsers 
>> That's right, the purpose of this pr is to show the topics instead of replies.

I don't think, users like it, when is subscribed a Feed, and it shows always the same first message.

My opinion:

### By Post : Post - Show the latests posts from the forum

- [x] Global feed : By Post - Shows the latests posts from the forum
- [x] Category Feed : By Post - Shows the latests posts from certain categories

### By Topic - Show the latest topics from the forum (topics only)

- [ ] Global Feed - Should show the last topics without content
- [ ] Category Feed - Should show the last topics fom certain categories without content

**Hint:** The ordering of topics is correct without this patch, it only needs to remove the content
### By Recent topics - Show the latest post from recently updated topics

- [x] Global Feed - Show the latest post from recently updated topics
- [x] Category Feed - Show the last post from recently updated topics from certain categories

**Comment by sshcli** [comment]
> I don't think, users like it, when is subscribed a Feed, and it shows always the same first message.

You are right, the Category Feed should work in the same way as the General Feed.
In this case, We can keep the issue opened, but I will close this PR now. 
Let's wait for a more profesional fix provided by the experts. 
Regards

**Pull request closed without merging**
