### PR TITLE
[Crypsis] Add button for all users: View poll results #1127

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] If you visit this topic, the result is already open
- [ ] The button is visible for all users
- [ ] All users see the result

**Comment by xillibit** [comment]
This change only when you see poll options in order to vote, if you have already voted to the poll you can see only the results.

It's intented that is available for all users : https://github.com/Kunena/Kunena-Forum/issues/1127#issuecomment-9268983, the name of pull request need to be changed...

**Comment by rich20** [comment]
The result is open as default. Also if they have not voted. With the button you can close it.

**Comment by xillibit** [comment]
@rich20 : try now i have updated it

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
