### PR TITLE
Add commas to separate moderators list

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by xillibit** [comment]
@rich20 : can-you test-it ?

**Comment by rich20** [comment]
Which list do you mean?

**Comment by xillibit** [comment]
In the bottom of a topic:

sqdsqds

**Comment by rich20** [comment]
> In the bottom of a topic:

Tank you
- [x] Comma is present now but there are two spaces afterwards. It's ok?

**Comment by xillibit** [comment]
I have just removed the extra space

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
