### PR TITLE
[K6.0] User related gravatars are not displayed #9289

### LINKED ISSUE #9289: User related gravatars are not displayed
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/166664-gravatar-not-working-on-j4-and-kunena-6
Confirmed
Custom gravatars are not displayed, instead only default gravatar images are displayed

**System information**
- Joomla version: 4.2.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.3
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #9289. 
 
Close #9289

#### Testing Instructions

### CODE REVIEW

**Comment by Leen29** [comment]
adjusted and tested but still the same as described here.
https://www.kunena.org/forum/general-questions-and-how-tos/166664-gravatar-not-working-on-j4-and-kunena-6
all users still get the same gravatar.

**Comment by rich20** [comment]
For me it works. For users who have registered their avatar at gravatar.com this image will be displayed, for all others the default gravatar image will be used.
.
Bildschirmfoto vom 2022-09-30 19-14-20

**Comment by Leen29** [comment]
line 20 says "use Pedrollo\GravatarLib\Gravatar;"
may i know what Pedrollo is ?
maybe that is causing my problem?

**Comment by Ruud68** [comment]
@Leen29 When developing functionality, you can also (re)use code from other developers. That is the case here for the gravatar functionality. Kunena is 'using' the code created by developer Pedrollo.

The benefit is that you do not have to reinvent the wheel yourself as the code is already available and functional.

In this case however, Pedrollo stopped coding and providing his Gravatar code: so this library is unmaintained.
The code is fairly simple so not expecting any issues here.

**Comment by Leen29** [comment]
@Ruud: Thanks for the explanation I was searching in joomla/kunena files for "Pedrollo" but didn't find anything that's why this question

**Comment by xillibit** [comment]
> line 20 says "use Pedrollo\GravatarLib\Gravatar;" may i know what Pedrollo is ? maybe that is causing my problem?

It's an external library, but just scss is autoloaded i will revert just this line of change

**Comment by Leen29** [comment]
@xillibit: Thanks

**Pull request merged**
