### PR TITLE
[k4.0] Crypsis hide more info for guests posts

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by Ruud68** [comment]
Hi, unfortunately it still shows the info.
when I change <?php if (!$user->guest) : ?>
to <?php if (!$user) : ?>
it does work

**Comment by 810** [comment]
updated the code, should work now

**Comment by Ruud68** [comment]
works :)
with this code in the same file you can also make the rank image (no added value for a guest?) also hidden for guests
        <?php if (!empty($rankImage) && ($user->userid > 1)) : ?>
        <li>
                <?php echo $rankImage; ?>
        </li>
        <?php endif; ?>

**Comment by 810** [comment]
I looked at it. But for ux i think we need have a guest rank. Looks cleaner for me.

**Comment by Ruud68** [comment]
:) cool with me :)

**Pull request merged**
