### PR TITLE
Add the possibility to generate report configuration in anonymous way

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Report Configuration - Success
- [ ] Report Configuration Anonymous -> Select all and copy - Failed

**Comment by 810** [comment]
sended a pr. But what are the changes on the view?

**Comment by xillibit** [comment]
There two textarea, one of them have some data removed like name of site, email address...

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
