### PR TITLE
add missing svg icons

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #9344 . 
 
#### Summary of Changes 
copy over missing svg icons from ./media/kunena/core/svg/default/[user|system]/svg to ./media/kunena/core/svg as that is used as fallback location
 
#### Testing Instructions
@rich20

### CODE REVIEW

**Comment by Ruud68** [comment]
@xillibit when looking at the comments.svg, they look good on the recent topics overview (smal in first column), but when viewing on the topic page itself, the icon is huge.
I noticed that the size of the icons I copied over in this PR are different in size, so when no size is provided they are displayed big.
maybe @rich20 can confirm?

This I do not get because on the whole kunena installation there is only one comments.svg and that was used previously on these pages and that is the one I copied over.

Do you know how we can get these files in the same size as the ones already in the svg directory (so the comments.svg)?

**Comment by rich20** [comment]
For me, the symbols are displayed correctly in all places. I have also tested it with a self-created svg image (size 450 x 530), which is also displayed correctly everywhere.

**Comment by Ruud68** [comment]
did you test with our without #9348
That has been merged now and that fixes it for for me

**Comment by rich20** [comment]
I had tested it before this fix, but had already uploaded the icons manually when I saw this error message.

> Warning: DOMDocument::load(): I/O warning : failed to load external entity "/.../media/kunena/core/svg/comments.svg" in /.../libraries/kunena/src/Icons/KunenaSvgIcons.php on line 76

Now is all ok!

**Pull request merged**
