### PR TITLE
Move more language string concatenations...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... out of PHP and into sprintf of language strings as per #5873.

Note: Rebased to remove non en-GB language string changes. For RTL languages strings (definitely those with parameters, but also those without but with mixed language would benefit) a Unicode RLE character should be inserted at the beginning and a Unicode PDF character should be inserted at the end in order to ensure that the translation is shown the same on LTR and RTL pages regardless of whether the substituted text is LTR or RTL. (Or perhaps this should be included in Joomla JText functionality.)

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Please note that I have not been able to test the language strings - as I only have a production site and do not have a multi-lingual test site built.

But an explanation of my thinking behind the RTL is as follows:

Suppose your substitution string is `COM_KUNENA_EDITING_LASTEDIT_ON_BY = "‫עריכה אחרונה: %1$s מאת %2$s.‬"`. Because Github displays RTL unicode correctly, the string is shown with the RTL parts reversed - and characters that are neither LTR or RTL get displayed according to what surrounds them. However the string is actually stored internally more like `‭עריכה אחרונה: %1$s מאת %2$s.‬‬` (which I have displayed here by starting it with a Left-to-Right Override (LRO) character).

If you don't do anything with special Unicode characters, when you substitute the %s with LTR strings you get a string which looks internally like `(RTL1): (LTR1) (RTL2) (LTR2)`. I think that without any special RTL embedded special characters then on an RTL page this will be displayed correctly as `(LTR2) (RTL2) (LTR1) :(RTL1)` but on a LTR page it will be displayed `(RTL1): (LTR1) (RTL2) (LTR2)` which probably makes little sense. `(RTL1): (RTL2) (RTL3) (LTR1)` would be displayed on an LTR page `(RTL3) (RTL2) :(RTL1) (LTR1)` which is a different order - and when the order of words depends on whether the words are in an :TR or RTL character set, that is pretty confusing.

By inserting a special Unicode Right-to-Left-Embedded (RLE) character at the beginning, and a Pop-Directional-Formatting (PDF) character at the end, then it will treat the entire phrase as a single RTL entity and display it consistently.

**Comment by 810** [comment]
You should only edit en-gb files, no other languages. They are will be merged by transifex.

Transifex will only merge the en-gb files.

**Comment by Sophist-UK** [comment]
The strings in the other files are identical to existing strings except for the parameters and should not be a problem if they are overwritten. The reason I included them was to avoid users suddenly getting the default English translations where they were previously getting translated versions until Transifex publishes the non-English versions of new strings which might take a couple of transifex cycles (o ne to upload the new English strings and another to download translations.

But if you wish, I can rebase this without the non-English language files. Let me know.

**Comment by 810** [comment]
You can better remove those, else there will be maybe a double string will be created, then its harder to debug, also the pr has now conflicts , because i remove the cs_CZ files

**Comment by Sophist-UK** [comment]
Note: I will remove them, however this will lose the special characters I have inserted in the RTL language files.

Can you make Transifex include these as standard?

**Comment by Sophist-UK** [comment]
Rebased to remove non-english translations.

**Pull request merged**
