### PR TITLE
Unapproved tab not available in crypsis #5489

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5489.

### CODE REVIEW

**Comment by sshcli** [comment]
Test results = OK✔

**Comment by 810** [comment]
It works, but should it be there at all? because it has nothing todo with the profile.

**Comment by sshcli** [comment]
> It works, but should it be there at all? because it has nothing todo with the profile.

I see your point

**The change is necessary?**
Yes

**Why?**
Because without this pr, there is no option to see all unapproved messages for specific user.

**Can we leave the tab as is?**
The tab It's only visible to moderators, so I think It won't have a negative impact for UX.
Also it was used for a long time in Blue Eagle 4.x without any complaint

**The view should be moved to another place?**
I believe in continuous improvement. It's up to you, it depends of your time to do it.
Enhances are always welcome.

**Comment by 810** [comment]
The best way is to show only own unapproved messages, Then we need to allow also topic author to open the topic, then they can also edit it

**Comment by xillibit** [comment]
> The best way is to show only own unapproved messages, Then we need to allow also topic author to open the topic, then they can also edit it

Why you want to allow topic author to open the topic ? Because only moderators and admin can see the unapproved tab

**Comment by sshcli** [comment]
@xillibit I think @810 is talking about this [enhance](https://github.com/Kunena/Kunena-Forum/issues/5381) that will be added in k.5.1

**Comment by 810** [comment]
yes, that one i want to include also on the pr.

**Pull request closed without merging**
