### PR TITLE
Updates CB Integration

### PR DESCRIPTION
**Pull request by krileon**
Updates URL usages and extends access with additional events to allow CB plugins to further control category access.

### CODE REVIEW

**Comment by 810** [comment]
thnx, will merge it. and will do codestyle, or can you fix the codestyle?

**Comment by krileon** [comment]
What code style are you using? Default phpstorm? If you've a custom phpstorm code style scheme please provide it or a reference to your styling guidelines.

**Comment by 810** [comment]
We use the default joomla codestyle rules.

**Comment by krileon** [comment]
Ok, I've updated the styling as per the guidelines below.

http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

**Pull request merged**
