### PR TITLE
Can't switch between avatar galleries in profile #3936

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #3936.

### CODE REVIEW

**Comment by 810** [comment]
Please also change crypsisb3

And the root is missing on the images.

**Comment by rich20** [comment]
- [ ] Failed - If you switch the folder, it shows only empty symbols

bildschirmfoto vom 2016-05-13 19 42 25

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
