### PR TITLE
[K3.0.8] Menu item Recent Posts shows only own posts #2816

### PR DESCRIPTION
**Pull request by 810**
Its must be userid, not username.

When login, own messages are showed, this is normal behavior i think.

### CODE REVIEW

**Comment by rich20** [comment]
>Its must be userid, not username.

>When login, own messages are showed, this is normal behavior i think.


I mean, it's not optimal. You know the own posts. Users want to see also the other posts.

**Comment by 810** [comment]
that's the recent topics part

**Comment by rich20** [comment]
hmm.. I don't understand this menu item.
Description: Recent Posts - Displays recent posts with a few options to choose from

**Comment by 810** [comment]
we need to fix it, in the mean time, i merge this language strings

**Pull request merged**
