### PR TITLE
[K3.1] Subscription : The option "Check Subscription Box = Yes or No" sh...

### PR DESCRIPTION
**Pull request by 810**
...ould be in the profile available

https://github.com/Kunena/Kunena-Forum/issues/2759

### CODE REVIEW

**Comment by rich20** [comment]
In principle it works, but if you have set in backend "Check Subscription Box = No", the setup in the profile has no effect. The checkbox remains empty if is set to Yes.

**Comment by 810** [comment]
its should be hidden when turned off "Check Subscription Box = No",

**Comment by rich20** [comment]
Then the user has again no choice.

**Comment by 810** [comment]
Ok try now

**Comment by rich20** [comment]
Kunena Installation Failed!
SQL Query: ALTER TABLE `#__kunena_users` ADD `userListtime` int(11) NOT NULL DEFAULT '-2' AFTER `canSubscribe`; ... FAILED

This error is present, if you want to install Kunena again.

**Comment by 810** [comment]
try again

**Comment by rich20** [comment]
- [x) All Subscriptions Options - Success
- [x) SQL Query -  Success

**Pull request merged**
