### PR TITLE
[K5.1] Attachment reference and content deleted on remove/all #5716

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5716 . 
 
#### Testing Instructions

### CODE REVIEW

**Comment by rich20** [comment]
If you insert images with the button "insert all" in messages and you remove one of this image with the button "Remove file", you get in the message field the word **false**. When you save then remains only this word in the message and from the rest of the images remain only thumbnails.

**Comment by xillibit** [comment]
@rich20 : can-you try now ?

**Comment by rich20** [comment]
Delete via backend or frontend file manager is for me ok now but only for attachments which have been inserted one by one. 

I don't understand why there is a difference on delete if you insert the attachments one by one or have been added with the button "Insert all".
If you use the button "Insert all" remain all codes, whether indifferent text is in the message or not.

## These issues exists only with attachments which are inserted with the button Insert All
**Edit message**

- [ ] Attachments which have been inserted with the button "Insert all" all will be removed from the text field if you want only remove a single attachment. It adds the word "**false**" in the text field instead.

**Frontend attachment manager**
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but all codes remain in the message

**Backend file manager**
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but all codes remain in the message

**Comment by xillibit** [comment]
> I don't understand why there is a difference on delete if you insert the attachments one by one or have been added with the button "Insert all".

Because it's two diffrents functions :remove with insert all and remove all files

**Comment by rich20** [comment]
There is also the option "Remove attachment from the list". But this option is only available, when the attachments would have been inserted one by one.
You see it on the image, I've added the first attachment with the button Insert All and here lacks this option.
Bildschirmfoto von 2020-04-11 19-59-32

**Comment by xillibit** [comment]
> There is also the option "Remove attachment from the list". But this option is only available, when the attachments would have been inserted one by one.
> You see it on the image, I've added the first attachment with the button Insert All and here lacks this option.

That's is something that @jelle has added but i don't understand exactly the purpose

**Comment by 810** [comment]
when the image is inline, then the image isn't showed on the attachment under the message.
Before it showed in the message and under the message on the attachment list.

**Comment by 810** [comment]
Please add insert all, on edit message.

Also when insert 3 from 6 images, all images are showed on the thumbnail bellow the message.

**Comment by xillibit** [comment]
> Please add insert all, on edit message.
> 
> Also when insert 3 from 6 images, all images are showed on the thumbnail bellow the message.

I will look at it

**Comment by 810** [comment]
ok, thats looking better, next issue: When insert all, skip files that already in the message.

**Comment by rich20** [comment]
The button "Remove All" removes itself if you click on it. It's indifference with which button the attachments have been inserted.
Reproduce it:
1. Add on reply one or more attachments in the message
2. Click on Remove All (it removes only the Remove All button the attachments remain)

**Comment by xillibit** [comment]
> ok, thats looking better, next issue: When insert all, skip files that already in the message.



> The button "Remove All" removes itself if you click on it. It's indifference with which button the attachments have been inserted.
> Reproduce it:
> 
>     1. Add on reply one or more attachments in the message
> 
>     2. Click on Remove All (it removes only the Remove All button the attachments remain)

I will fix that in another PR

**Pull request merged**
