### PR TITLE
Attachment manager limited to 30 (fix from rtv3)

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .
#### Testing Instructions

This change add pagination into tab attachments in your profile, so if you have  more than 30 attachments you will see pagination

### CODE REVIEW

**Comment by 810** [comment]
fix doesn't work, I still see 30 attachments

**Comment by xillibit** [comment]
There is missing the pagination that's part i have found to add it, but after it missing the view to display the list of attachments

**Comment by rich20** [comment]
If you go the next page
Warning: include(.../components/com_kunena/template/crypsis/html/display.php): failed to open stream: No such file or directory in libraries/kunena/view.php on line 125

**Comment by xillibit** [comment]
i had noticed that but i think it's missing the view to see attachments list

**Comment by rich20** [comment]
- [x] Success

**Comment by sshcli** [comment]
- [x] Success

**Pull request merged**
