### PR TITLE
Handle protected attachments the same as non-protected attachments

### PR DESCRIPTION
**Pull request by Pinkeltje**
Pull Request for Issue #9769  . 
 
#### Summary of Changes 
When setting Protect Attachments to Yes, protected attachments are now "behaving" like non-protected attachments
When testing discovered another bug: When saving message first and then edit and insert attachment, id was not retreived. Result: `[attachment=undefined]hash[/attachment]`
#### Testing Instructions
Please test carefully, because there ar so many variables in this file.

### CODE REVIEW

**Comment by rich20** [comment]
Now it doesn't work properly even without protecting attachments. I have uploaded three attachments. 
One not inserted in the message
one inserted in the message
set one as private
Bildschirmfoto vom 2024-12-21 17-35-07

--------------------------------------
## Result if you click on edit
g20397

**Comment by Pinkeltje** [comment]
Think it is ok now. Took me a while to find that protected attachments have value 1 in field protected in attachments table where as private attachments have value 32.

**Comment by Pinkeltje** [comment]
@xillibit latest commit is concerning 
https://www.kunena.org/forum/k-6-3-0-support/168674-incorrect-use-of-label-for-from_element#232590
Chrome thinks that labels should match id.

**Comment by xillibit** [comment]
My commit change for the title input for quickreply on a subject, when i look with developper tools i have label and id matching : `<div class="form-group">
                                <label for="subject103" class="col-md-12 control-label" style="padding:0;">
                                    **Subject**:
                                </label>
                                <input type="text" id="subject103" name="subject" class="form-control" maxlength="80" value="topic test">
                            </div>`

**Comment by Pinkeltje** [comment]
Yes, that one is ok. So shouldn't be changed. Maybe create seperate issue for Chrome and label "errors". My pull request was added automatically to this pull request, but it gets confusing now.

**Comment by rich20** [comment]
- [x] Fix for protected attachments - Success
- [x] Label issue Chrome - Chromium no longer shows an error, so I think it also works with Crome

**Pull request merged**
