### PR TITLE
Fix: inconsistant language string naming > bsky_app - bluesky_social …

### PR DESCRIPTION
**Pull request by Ruud68**
…+ link typo fix

Pull Request for Issue # . 
Reported by [@Gindi50](https://github.com/Gindi50) here: https://github.com/Kunena/Kunena-Forum/pull/9622#issuecomment-1949927940 and here: https://github.com/Kunena/Kunena-Forum/pull/9622#issuecomment-1951315301
 
#### Summary of Changes 
* fixed hhttps type
* changed language string from bluesky_social to bsky_app as that is was is used to programmatically create the language string for this social media platform
 
#### Testing Instructions

### CODE REVIEW

**Comment by Ruud68** [comment]
https://github.com/Gindi50 can you test this one: not both php and two language .ini files changed
I only tested back-end my self, not front-end

**Comment by Gindi50** [comment]
After the changes, "BlueSky social" is displayed in the frontend of Kunena's profile below Reddit.
Everything is fine now.
Also in the backend everything is now displayed correctly, unfortunately in English.
Now I'm looking for the place where it can be translated into German.
Thank you.

**Comment by Ruud68** [comment]
When PR gets accepted, the language files will be uploaded to transitex where they are translated by volunteers. So when all is dan and 6.3 is released all translation should be okay 👍

**Comment by Gindi50** [comment]
I have copied the section "Back-end Filter strings" from the English en-GB.com.kunena.views.ini into the German de-DE.com.kunena.views.ini and translated the terms.
Now everything is displayed in German.

**Pull request merged**
