### PR TITLE
[4.0][blue eagle] Allowed File Types Field not Working #3082

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] Failed - All files are changed to the last uploaded file

**Comment by xillibit** [comment]
Are-you trying to upload always the same file (this is this issue : https://github.com/Kunena/Kunena-Forum/issues/3110) ?

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
Sorry, yes I had tested #3110. It works now.

**Pull request merged**
