### PR TITLE
SEO: Convert blank lines to space in meta description #6255

### LINKED ISSUE #6255: SEO: Convert blank lines to space in meta description
**To Reproduce**
1. Create a topic and include blank lines in content. You can use the following example:
```
Lorem ipsum dolor sit amet. 

consectetur adipiscing elit. 

Sed do eiusmod tempor. 

Incididunt ut labore et dolore magna aliqua. 

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
```
2. View source code of the page

**Expected behavior**
Blank lines should be converted to spaces in meta description, og:description and twitter:description
good3

**Actual result**
Blank lines are not converted to spaces in meta description, og:description and twitter:description
bad3

**System information (please complete the following information)**
Joomla version: 3.9.3
Kunena version: 5.1.11-DEV
Php version: 7.3.2
Database version: MySQL 5.7.25

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #6255.

Close #6255  
 
#### Testing Instructions

### CODE REVIEW

**Comment by xillibit** [comment]
@sshcli : can-you check it please ?

**Comment by sshcli** [comment]
Test Results -> og:description = ✔️ / Pass / OK / Success
Test Results -> twitter:description = ✔️ / Pass / OK / Success

Test Results -> meta description =  ❌Fail
Details: Must add $multispaces_replaced also for meta description

**Comment by xillibit** [comment]
@sshcli : try now

**Comment by sshcli** [comment]
Test Results -> meta description = ✔️ / Pass / OK / Success

**Comment by sshcli** [comment]
RTC

**Pull request merged**
