### PR TITLE
[K5.2] Limit allowed BBCode for the new users (no urls, images) #278

### LINKED ISSUE #278: Limit allowed BBCode for the new users (no urls, images)
See:
http://www.kunena.org/forum/119-feature-requests/20773-limit-posts-by-new-users-to-prevent-spam?limit=10&start=10#114149

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #278. 
 
If needed close #278

### CODE REVIEW

**Comment by xillibit** [comment]
Improvements to be made, see the old PR : https://github.com/Kunena/Kunena-Forum/pull/7666#issuecomment-725477128

**Comment by xillibit** [comment]
@rich20 : can-you try now ?

**Comment by rich20** [comment]
- [ ] If the option enabled, the normal user cannot use BBCode at all such as bold, confidential and so on (also not when the limit is reached).
- [ ] Wrong message: Your message has been successfully posted. (there should be a hint when BBCode has been removed)
- [x] Links added with BBcodes, and also entered links without code will removed (it remains only the brackets)

**Comment by rich20** [comment]
@xillibit If a link has been removed it remain two brackets instead of the link. () Should be there the hint in it?

**Comment by xillibit** [comment]
It does when you just putting a link in message like that  : 

image

?

In this case it just remove the link and i don't see the two brackets ()

P.S.: if i use a link like this one `https://www.kunena.org/forum/kunena-latest-m-archive/156737-php-7-3-and-leatest-post-module-is-show-nothing?start=10#214381` when i submit the message it remains the `?start=10#214381`

**Comment by xillibit** [comment]
With the last change it is able to find too this kind of url : `https://www.kunena.org/forum/kunena-latest-m-archive/156737-php-7-3-and-leatest-post-module-is-show-nothing?start=10#214381`

**Comment by xillibit** [comment]
The last update is able to recognize this kind of url too : `https://www.kunena.org/forum/kunena-latest-m-archive/156737-php-7-3-and-leatest-post-module-is-show-nothing?start=10`

**Comment by rich20** [comment]
>In this case it just remove the link and i don't see the two brackets ()
With the last change it is able to find too this kind of url: `https://www.kunena.org/forum/kunena-latest-m-archive/156737-php-7-3-and-leatest-post-module-is-show-nothing?start=10#214381`

Depending on the length or type of the url you get different results.
Example: I've entered 2 link addresses with and without BBCode. You see on the second image the result.
Bildschirmfoto von 2020-11-15 16-16-39
Bildschirmfoto von 2020-11-15 16-16-55

**Comment by xillibit** [comment]
In this case i can't post the message : 

image

**Comment by rich20** [comment]
>In this case i can't post the message :

I've cleared all caches, now I can reproduce your message. That's not an error, because the message contains not another text and without text can't be saved.
I've tested also the other codes such as confidential, bold and so on. They're working correctly now. Indeed, I found another issue, but I will create an own ticket for it.
So I mark this pull request as done.

- [x] Success

**Pull request merged**
