### PR TITLE
Text area now expand in vertical way only (chrome)

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue https://github.com/Kunena/Kunena-Forum/issues/5319

### CODE REVIEW

**Comment by rich20** [comment]
Not optimal. With this code you also cannot change the height of the text field.

**Comment by sshcli** [comment]
it should work now.
Please test again

**Comment by rich20** [comment]
- [x] Yes, it's better now.

Please check also quick reply

**Comment by sshcli** [comment]
The quick reply is working OK for me.
Can you please clear the cache and try again?

**Comment by rich20** [comment]
- [x] Yes it works. It was not the cache, the browser tool had no recognised the code.

**Pull request merged**
