### PR TITLE
[K3.1] Search: increase default date time option

### PR DESCRIPTION
**Pull request by 810**
https://github.com/Kunena/Kunena-Forum/issues/2121

### CODE REVIEW

**Comment by coder4life** [comment]
We cannot actually use this commit for security and performance reasons.  If you notice even Google does not allow queries over a certain time period past 365 days as seen here:
https://www.google.com/?gws_rd=ssl#q=google&tbs=qdr:y
What google does allow is a custom range over a certain time period, even older then 365 days.  We should be able to set a custom range with that range having a maximum of 1 year.

**Comment by 810** [comment]
I'm disagree with you. This is not a security or performance issue. I set it to 365 days as default, so users can choose other time dates, if they want. Now they must edit the file on each release. 

If you have a big website, you should stay on 365. 

@mahagr are you agree with me?

**Comment by coder4life** [comment]
@mahagr is actually the one that advised me on this.  I agree it could be an option, however before I accept this commit please make a descriptive warning about setting dates too high, as the reason I closed this pull request is for the fact that people could shoot themselves in the foot.  This is one of those options where we want to discourage potential performance bottlenecks people could create for themselves.

**Comment by 810** [comment]
i have updated the pr. can i merge it?

**Pull request merged**
