### PR TITLE
Implement Bbcode editor markitup in crypsis

### PR DESCRIPTION
**Pull request by xillibit**
- [x] Remove double color icon on dropdown
- [x] Remove last button "Clean"
- [x] Add Twitter button
- [x] Add HR icon
- [x] Add options "Code" on modal
- [x] Add options "Maps" on modal (no add button, missing zoom)
- [x] Add btn class for button add/remove Poll
- [x] Hide Add button Poll if max option is reached (should be gone 1 sooner)
- [x] Missing some language strings
- [x] Remove white background twitter icon
- [x] remove poll icon on reply, is now empty modal
- [x] Maybe we need to change the text to add on close. and add cancel button ?
- [x] Add Emoticons (need styling ?)
- [ ] The colors drop down is displayed in the background of others buttons

### CODE REVIEW

**Comment by 810** [comment]
missing closing tag }
https://github.com/xillibit/Kunena-forum/blob/bbcode_editor_markitup/components/com_kunena/site/template/crypsis/less/editor.less#L691

to much closing tag }
https://github.com/xillibit/Kunena-forum/blob/bbcode_editor_markitup/components/com_kunena/template/crypsis/layouts/topic/edit/editor/default.php#L139

Issue with icons on edit

**Comment by xillibit** [comment]
I have fixed these three things

**Comment by 810** [comment]
#### Todo's
- [ ] Remove double color icon on dropdown
- [ ] Remove last button "Clean"
- [ ] Add Twitter button
- [ ] Add HR button
- [ ] Add options "Code" on modal
- [ ] Add options "Maps" on modal
- [ ] Add btn class for button add/remove Poll
- [ ] Hide Add button Poll if max option is reached

**Comment by xillibit** [comment]
> Remove last button "Clean"

Why removing it ?

> Add options "Maps" on modal

Which options ?

> Add btn class for button add/remove Poll

Do-you mean to add or remove the poll options ?

**Comment by 810** [comment]
> Remove last button "Clean"
> Why removing it ?
because its for cleaning the code, but all code is already correct.

> Add options "Maps" on modal

> Which options ?
like zoom, type map

> Add btn class for button add/remove Poll
> Do-you mean to add or remove the poll options ?
the + and - icons should add class="btn btn-small"

**Comment by xillibit** [comment]
I have updated my PR

**Comment by 810** [comment]
See list ^^

**Comment by xillibit** [comment]
> Add Twitter button (use sprite icon)
> Add HR button (use sprite icon)

In the editor.less that you had modified before for this PR, it seems you don't use sprite file for icons of editor : 

```css
.markItUp .markItUpButton23 a {
background-image: url(images/film.png);
}
.markItUp .markItUpButton24 a {
background-image: url(images/map.png);
}
.markItUp .markItUpButton25 a {
background-image: url(images/poll.png);
}
.markItUp .markItUpButton26 a {
background-image: url(images/tweet.png);
}
.markItUp .clean a {
background-image: url(images/clean.png);
}
```

**Comment by 810** [comment]
ok updated

**Comment by xillibit** [comment]
Updated, things which are done : 

- [ ] Remove last button "Clean"
- [ ] Add Twitter button
- [ ] Add HR icon
- [ ] Add options "Code" on modal
- [ ] Add options "Maps" on modal (no add button, missing zoom)
- [ ] Add btn class for button add/remove Poll
- [ ] Hide Add button Poll if max option is reached (should be gone 1 sooner)

> Add options "Maps" on modal (no add button, missing zoom)

It's normal that there is no add button because when you close modal, the bbcode is added in the form

**Comment by 810** [comment]
- [ ] Map is always on top (inserted on top)
- [ ] Remove white background twitter icon
- [ ] remove poll icon on reply, is now empty modal

**Comment by rich20** [comment]
The code buttons are not available on Edit

**Comment by xillibit** [comment]
For emoticons is available via autocomplete : 

dsfbg

**Comment by xillibit** [comment]
I have updated twitter icon to set transparent background and now if you are on reply the poll icon doesn't open modal

**Comment by 810** [comment]
yes, i would like a bbcode button with emoticon icon, that's have a dropdown with all emotions.

**Comment by xillibit** [comment]
For emoticons i can do a button which open a modal box to choose the emoticons, i'am not able to do a drop-down

**Comment by 810** [comment]
Ok, i can do that. if you add the code, i will restyle it.

- the colors are gone on the dropdown. always same icon

You removed code modal?

**Comment by xillibit** [comment]
Code modal appears only if you have enable hightling in backend else it insert just [code][/code] that it's the same behaviour that under blue eagle

**Comment by 810** [comment]
ok cool, could you change the text on modals to "Add"

**Comment by xillibit** [comment]
> ok cool, could you change the text on modals to "Add"

It's the thing that i'am on it actually after i will do the modal for the emoticons

**Comment by xillibit** [comment]
The PR is updated with Add button on modal

**Comment by 810** [comment]
- [ ] Link modal, isn't insert bbcode
- [ ] Map modal, puts bbcode on top off message, not on position

**Comment by xillibit** [comment]
> Link modal, isn't insert bbcode

Fixed

> Map modal, puts bbcode on top off message, not on position

I don't reproduce this issue

**Comment by 810** [comment]
On IE, the bbcode insert is always on top. (All modals)

**Comment by rich20** [comment]
The drop down are in background.

**Comment by 810** [comment]
on map modal. 
when you enter city, the bbcode is adding to the message, So you can't switch zoom anymore

**Comment by xillibit** [comment]
> On IE, the bbcode insert is always on top. (All modals)

I have tried with IE too, but the bbcode is inserted right where i have the cursor

> The drop down are in background.

I know but for now i don't know how to fix it

> on map modal.
> when you enter city, the bbcode is adding to the message, So you can't switch zoom anymore

It adds the bbcode when you fill the field ctiy, i need to change for all modal to insert bbocde when you hit Add button

**Comment by 810** [comment]
> On IE, the bbcode insert is always on top. (All modals)

> I have tried with IE too, but the bbcode is inserted right where i have the cursor
Ok, maybe its because my IE version. Running IE11.0.8 And Win 10 Build 9926

**Comment by xillibit** [comment]
> Ok, i can do that. if you add the code, i will restyle it.

I have updated to add modal for smilies, you can now

**Comment by 810** [comment]
ok colors and merge left

**Comment by xillibit** [comment]
> on map modal.
>     when you enter city, the bbcode is adding to the message, So you can't switch zoom anymore
> 
> It adds the bbcode when you fill the field city, i need to change for all modal to insert bbocde when you hit Add button

I have just changed that

**Comment by rich20** [comment]
Enable Code Highlighting : After add - you must place the cursor manually

**Comment by xillibit** [comment]
Place manually the cursor where ?

**Comment by rich20** [comment]
>Place manually the cursor where ? Into the bbcodes when you add it ?

[code type="css"]here you must place manually the cursor[/code]
The problem with all modal settings, you leave the text field and come no back automatically. It needs more steps as with Blue Eagle.

**Comment by xillibit** [comment]
@810 : are-you able to fix drop-down issue to make appear above the buttons which are below ?

**Comment by 810** [comment]
yes, if you can change the behavior, just like color.

**Comment by 810** [comment]
Could you add dropzone back also the files on editor.less

**Comment by xillibit** [comment]
Because there was a conflict on the file editor.less, i think i have made a mistake when fixing the conflict

**Comment by xillibit** [comment]
@810 : updated now

**Pull request merged**
