### PR TITLE
add dropstart on mobile view

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #9299 . 
 
#### Summary of Changes 
add BS5 'dropstart' to dropdon on mobile
 
#### Testing Instructions
@rich20

### CODE REVIEW

**Comment by rich20** [comment]
When logging in it works, but when you are logged in, the dropdown menu is again on the right outside the screen

**Comment by Ruud68** [comment]
@rich20  just added the dropstart to the dropdownmenu as well. note that this is for all devices as they share the code base. So also on desktop it has changed now.

**Comment by rich20** [comment]
I think it's ok like this, then it also fits for the Fluid Desktop view (without modules on the right), there it was also outside the screen.

**Comment by fotofreunde** [comment]
Screenshot_149
unfortunately everything goes to the left side.
And login does not work on the smartphone.

**Comment by fotofreunde** [comment]
Yes I did everything.
Unfortunately, everything is duplicated on the smartphone.
Screenshot_152
Screenshot_153

**Pull request merged**
