### PR TITLE
K3.1 Feature: max links (spam feature) #2499

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by sozzled** [comment]
This "max links" feature (anti-spam) has a few problems with it.  I have a few questions about the appropriateness of the way the feature may have been implemented.

Firstly, has this idea been implemented in K 4.0 and, if so, where is the discussion about it?

**Comment by 810** [comment]
You can ask the question on the forum.

**Comment by sozzled** [comment]
I would like to ask my questions here, please.

Have you implemented this feature in K 4.0?  Is there some discussion about how the feature is implemented?

**Comment by 810** [comment]
Yes, its in K4.0.

In the code you see how its works. 

Its counting the 
- http
- href 
- [url 
links in a message

**Comment by sozzled** [comment]
My problem is *how* this anti-spam feature has been implemented.  If I understand correctly (correct me if I have not understood it properly), this anti-spam feature is turned on by default.  The way I understand it to work is that, if a person tries to post a message with more than 6 links in it, the message is not posted on the forum.  Is that correct?

If this is correct, this is a very different way that K 4.0 operates to the earlier versions where "anti-spam" mechanisms are turned *off* by default (for example the "anti-flood" feature and the "moderate new users" feature).

**Comment by 810** [comment]
Yes, its enabled by default as Max 6 links in a message. That number is a normal number by default forum users. If you are going to post more links, like on a game/news forum, you should increase the number.

But for the most forum users (90%) this number will be good to prevent spam.
I turned this feature on by default, because we want to decrease the total spam on Kunena Forums.

**Comment by sozzled** [comment]
In my opinion, this is not normal.  
I have a different view.

Nearly all the other "anti-spam"/security mechanisms in the Kunena configuration are turned off by default.  In this way, people can install Kunena and use it immediately.  If they have problems (with spam messages) they can enable some of Kunena's security mechanisms to deal with potential problems.

Most users, from my experience, do not have problems with spam.  Those who do have problems with spam can enable some of Kunena's features to prevent spam "attacks".  They can moderate new users, set a time limit between posting (anti-flood) et cetera.

Again, I ask, where was the discussion with other contributors to the Kunena development, to decide (a) to turn this max links feature ***on*** by default, and (b) to set the value of 6 max-links as the initial/default value?  I cannot find any discussion where this idea was agreed by other contributors to the Kunena project.  Can you show me where this discussion occurred, please?

**Comment by 810** [comment]
anti-flood is set to "0" because off the decrease in speed. We are reviewing the features, And removing some in K4,1. Like: Stop Forum Spam/Kunena Captcha (Only Joomla captcha will be supported)

As you know, We talk our discussions internal. Not for public.

**Comment by sozzled** [comment]
So, what you are telling me is this:  Kunena is open source but the decisions on how to implement the design, development and execution are all done in secret?

**Comment by 810** [comment]
No, that's not what I say. 

Everyone can contributor to Kunena, but the Management Team decides of a "Fix" or "New feature" will be merged or not.
 
Not all ideas are good, or need extra code to get it working better.

Everyone can contribute to the Kunena Project by sending Pull Requests. Then the Management Team will review the code, and necessary of the PR.

**Comment by sozzled** [comment]
In that case, I am reviewing the issue here and now.
In my opinion, the implementation of the max-links feature has been poorly executed.  It's not a bad idea to be able to limit the number of links contained in a message posted on a forum but it should be left to the forum owner to decide (a) whether they want to implement the feature and (b) what threshold to set.
There are few—if any—other settings in the Kunena configuration that forum owners need to change.
By setting the value of Max links = 6 (as an initial, default value) and, by not placing a clear warning to forum owners that this may impact on their users who like to include links to other sites in their messages, this is what we call a "gotcha".
"Gotchas" are not good.  "Gotchas" are things that make people wonder what ***else*** they may need to change in the Kunena configuration settings.
In my opinion, I think you got the idea half-right but the execution and the implementation of the feature was wrong.  In my opinion, this feature should be turned off by default (allow unlimited links) and, if forum owners find that their forums are being used by spam users, they can turn the feature on ***if*** they require it, not because you thought it was a good idea to turn it on in the first place.

**Comment by sozzled** [comment]
Matias wrote https://github.com/Kunena/Kunena-Forum/pull/2518#issuecomment-45254144 "Good feature ... I just need to think if there's a better way to do it so that there's more control on how it behaves."
I am saying the same thing.  I would like you to re-open this issue and change the default value in the Kunena configuration settings to turn the feature off.  Forum owners can then decide, themselves, if they want to implement the feature later.

**Comment by rich20** [comment]
> In my opinion, this feature should be turned off by default (allow unlimited links) and, if forum owners find that their forums are being used by spam users, they can turn the feature on if they require it, not because you thought it was a good idea to turn it on in the first place.

This is the key point what you say. If you would have the same written in the forum, the complete discussion here would have been unnecessary.

**Comment by sozzled** [comment]
If this idea had been discussed here, in Github, ***before*** it was implemented in K 4.0, there would not have been the question asked on the forum. http://www.kunena.org/forum/k-4-0-general-questions/133871-can-t-create-new-topic-maybe-limit-in-characters

The whole point about Github is to discuss these kinds of ideas ***before*** they are implemented, true?  Or do you have another suggestion where people can discuss various ideas, ***before** they are implemented, in an open and public way?  Or, as I think some people may suspect, you do not want to canvas public opinion?

In any event, I believe this issue should be re-opened and that the default value should be changed.

**Comment by 810** [comment]
Github is for reporting issues, and contribute code. Not for discussing ideas.

for ideas you should do on: http://www.kunena.org/forum/kunena-4-0-feature-requests

**Comment by sozzled** [comment]
Since when did ***that*** happen?  The developers of Joomla use Github for discussing the ***implementation*** of ideas as well as for discussing the actual code development itself; even Jelle has done this.  So I disagree with your "definition" of the purpose of GitHub. 

Kunena is an open-source project.  Please do not quarantine discussions about how things are managed so that it ceases to be truly open souce.

If Github is not for discussing ideas, giving feedback, contributing to the ***implementation*** of how software will be delivered, and if there is no other avenue for providing that kind of feedback to the team, where else do you suggest we discuss these things?

Again, I repeat my request.  Please re-open this issue, change the ***default*** value of the Max Links setting so that, effectively, the feature is disabled by default and allow forum owners to turn it on if they require it.

**Comment by coder4life** [comment]
"This "max links" feature (anti-spam) has a few problems with it. I have a few questions about the appropriateness of the way the feature may have been implemented."
This is an analysis of personal concern, and does not represent issues with the actual implementation. Our bug tracker is for the consultation and development of the implemented decisions, not chit-chat about the merit and moral reasoning of why the team made the decision. As @810 pointed out the format and place to do this is in the forums.

"You have conveniently overlooked the fact that Matias wrote his opinion earlier in this discussion; he did not "contribute" to the code development. He simply gave his feedback. That's exactly what I am doing, too."
Correct Matias is involved as a team member at http://kunena.org/team, and thus he is discussing the issue appropriately. He also consults some of the larger changes to Kunena-Forum and represents a voting interest of major changes. His ongoing contributions to the project in the past, and current consultations of knowledge of the software means he is a valuable position to our team.

"Kunena is an open-source project. Please do not quarantine discussions about how things are managed so that it ceases to be truly open souce."
Open source is freedom to fork and reuse code. The mechanism in which the team communicates is determined separately. To clarify, we practice a lot of the same development mechanisms other organizations employ with open source development communication. In our case we use simple group voting procedures our team management agrees too in those decisions. As a little insight to those external to the available knowledge, a group of 5 team members currently look over the decisions of software implementations. People may of noticed an uptick in releases coming forward, this was to help accelerate some backlog of decision issues that were piling up. We internally discuss these decisions, and then discuss the best way to tackle implementing them. As such those building the software have creative interest and control over the direction of the software for bugs, features, and ideas. That is not saying we are not willing to listen to the community, if we did not listen to our members no one would be relying and using the forum software and we suffer reputable interests in installations. The team is at discretion of how the software is implemented and what they want to implement. That is the inherit risk of using software not your own as there is a controlling interest involved. However because of the license involved, open source allows the freedom of people to take the source code and modify it to how they see fit because of the GPL license.

To empathize those new to bug trackers mistakes will happen and questions get posted here all the time. We also understand some organizations treat bug trackers differently and allow questions. We will politely ask everyone to do it in a place that is most convenient for our team. Also since developers and those that are consulting with us work more closely to the design, development, and implementation of the software.

Also we read as much feedback as time allows and even if we do not answer our developers/designers do take an interest in proposals. So do not feel like you are being left out. We are committed to makie the best forum software possible.

The format and where to communicate personal opinions is best reserved for the forum. 


Also presentation is key on how to convey a report and not a question which requires us to respond differently. As a recommendation of how the post could of been made to make it a relevant issue that requires us to respond differently:

Modified:
This "max links" feature (anti-spam) feature should not be enabled by default due to past behavior of this feature. This feature creates problems...

**Comment by sozzled** [comment]
Perhaps I had better explain exactly what is wrong with the way that the feature, as implemented, is wrong (in my opinion, of course):
1) Look at the other security settings that currently exist in Kunena (where forum owner allows posts from "trusted"/registered users):

* Allow Guests to Post/Write: 	Disabled by default
* Moderate New Users: Disabled by default
* User Can Delete Own Post: 	Disabled by default
* Show Deleted Messages: Disabled by default
* Allow Username Changes: Disabled by default
* Flood Protection: Disabled by default
* Max Links:  ***Enabled*** by default

2) By setting Max Links = 6, this restricts the forum moderators and site administrators, too.  There are no other settings in Kunena that restrict the forum moderators and administrators in the way that this has been done with this new setting.

3)  The idea was not properly considered, discussed, or argued properly before it was implemented. The way things look, it was implemented simply because someone thought it was a good idea to implement it before it had been properly considered.

4) The implementation has already caused at least one problem (as reported at the forum on Kunena.org.

5)  You (Josh), Jelle and Rich have tried to shut down this discussion here and asserted that my criticism was inappropriate for GitHub.  And yet, there are many other examples in Github where we have had these kinds of discussions.  This is not just an issue about whether the code works—it's not even a discussion about whether the idea is necessary—it's a discussion about the way that the idea was implemented.

6)  You, Jelle and Rich seem to be making it extremely difficult for people to contribute their thoughts to improve the overall quality of Kunena and to make things easier for people to use it.

7)  As far as the team's discretion is concerned, I respect your right to acknowledge or refuse input as the case may be.  By the same token, however, this should not prevent a frank, honest and candid appraisal of different views held by different people.

8)  Matias asked for your input, Josh, over one week ago.  Perhaps you might be able to explain why you have only now taking the trouble to write a non-responsive reply in order to refute my claims that something was badly designed.

9) I repeat my request—a request that has not been addressed—to consider the points that I have made above, to re-open this issue and address it properly.  I request that the Max Links setting be "turned off" by default and allow forum owners to implement the feature if and when they feel it becomes necessary.

**Comment by coder4life** [comment]
Please post at http://www.kunena.org/forum/index for any further questions or concerns. I think we have been more then clear and fiar what Github is used for and you seem to keep ignoring our suggestion. We could pick apart each part of each others post and it does nothing to further the outcome. I think we have been fully open about where people can express their concerns and opinions outlined. I have locked this from any more comments due to the fact this is a Pull Request which has already been merged. If you like to improve the feature feel free to send a pull request, but the decisions have been made up to this point and we will take any valued feedback in the requested format we asked for.

**Pull request merged**
