### PR TITLE
Upload image fails by file limit

### PR DESCRIPTION
**Pull request by 810**
- this will create a new bug, that all images are resized

### CODE REVIEW

**Comment by rich20** [comment]
The upload works with this fix, but now it doesn't matter if is set Maximum Image File Size and Maximum File Size high or low. You can attachments upload without size limit.

**Comment by xillibit** [comment]
@rich20 : is-this still exists ?

**Comment by xillibit** [comment]
@sshcli and @rich20 : this issue still exists in Kunena 5.0.1 ?

**Comment by sshcli** [comment]
@xillibit @rich20
Tested in K.4.0.11, the size limit is working for me.
error

I will test now in K.5.0.1

**Comment by sshcli** [comment]
@xillibit @rich20
Tested in K.5.0.1, the size limit is working for me.
error2

**Pull request merged**
