### PR TITLE
Topics in trashbin are not showing the IP #5661

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5661.

### CODE REVIEW

**Comment by 810** [comment]
Error

Unknown column 'a.a.id' in 'order clause'

Notice: Undefined variable: count in C:/Users/Jelle/Documents/gitkraken/Kunena-Forum/src/libraries/kunena/database/object/finder.php on line 280


Notice: Undefined variable: results in C:/Users/Jelle/Documents/gitkraken/Kunena-Forum/src/libraries/kunena/database/object/finder.php on line 227

**Comment by xillibit** [comment]
Should be ok now

**Comment by 810** [comment]
code is correct, but can you change the order, the same as on messages

**Comment by xillibit** [comment]
By default it's the same, it order by id like messages

**Comment by 810** [comment]
i mean Author - Date - IP - ID

**Pull request merged**
