### PR TITLE
Add email layouts under system for url issue with blue eagle

### PR DESCRIPTION
**Pull request by xillibit**
See: http://www.kunena.org/forum/k-3-0-general-questions/132085-new-post-email-notification-url-broken?start=40#166352

### CODE REVIEW

**Comment by xillibit** [comment]
@rich20 : can-you test-it ?

**Comment by rich20** [comment]
The error still exists.
address in the mail
index.php?option=com_kunena&view=topic&catid=86&id=14459&mesid=26064&Itemid=108
goes to
index.php?option=com_kunena&view=home&defaultmenu=109&Itemid=108

**Comment by xillibit** [comment]
The mail should render in the same way that crypsis, when you click on the link you should be redirected to the topic

**Comment by rich20** [comment]
With Crypsis it goes directly to the message, but with Blue Eagle to the Kunena start page.

**Comment by xillibit** [comment]
I have just tried with SEF on and off in Kunena, the url in subscription mail goes always to the right message in the topic

**Pull request merged**
