### PR TITLE
Wysiwyg Editor - Insert uploaded image in message is not possible #5346

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #54346 .

### CODE REVIEW

**Comment by 810** [comment]
We do still need the old one also.

You can switch editor on : edit template - crypsis - bbcode - Editor

**Comment by xillibit** [comment]
Why you keep the other editor ?

**Comment by 810** [comment]
becuase Wysiwyg Editor has some/many issues. So user can always deceit if he want to use the legacy editor. Also for using plugins ect.

**Comment by xillibit** [comment]
I have updated it

**Pull request merged**
