### PR TITLE
Aurelia bootstrap optional

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue:
When you have a bootstrap theme other then Joomla Build in, then Kunena will load (possibly) conflicting / double bootstrap files
 
#### Summary of Changes 
This change introduces load bootstrap template parameter (default = yes). When set to yes it will work as before, when set to no Kunena will not load the Joomla Bootstrap files but depends on the template to load the bootstrap files
 
#### Testing Instructions
On Cassiopedia Template:
before PR: load forum > all should be working
after PR: load forum > all should be working

### CODE REVIEW

**Comment by xillibit** [comment]
When you do codestyle please make it in a separate PR else it's hard to understand the changes

Do-you have added new languages strings ?

**Comment by Ruud68** [comment]
Hi @xillibit, code style is automatically triggered by vscode, I will redo the change with minimum / no codestyle changes.
No new language strings used, the one used was already there as that config option existed in crypsis. So building on that one.

**Comment by Ruud68** [comment]
@xillibit can you recheck. The changes in language files and yml are in there because I did a rebase yesterday: no idea how to remove these from the PR, but they should not be conflicting as they are already merged in other PR's

**Comment by xillibit** [comment]
Seems better

**Pull request merged**
