### PR TITLE
We need a setting option "User can edit poll if no votes" (Part 3) #5975

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5975  . 
 
#### Testing Instructions

### CODE REVIEW

**Comment by 810** [comment]
please do crypsisb3 also

**Comment by rich20** [comment]
- [x] User can edit poll if no votes = Not allow edit - You get the message: You aren't allowed to edit the poll
- [ ] User can edit poll if no votes = Allow to edit - The changes will not saved (you get only the message : The message has been successfully edited.)

**Comment by xillibit** [comment]
I will check

**Comment by xillibit** [comment]
@rich20 : try now

**Comment by rich20** [comment]
- [x] User can edit poll if no votes = Not allow edit - Success
- [x] User can edit poll if no votes = Allow to edit - Success

**Pull request merged**
