### PR TITLE
new menu item: recent posts/topics for unread messages #5657

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5657.

### CODE REVIEW

**Comment by 810** [comment]
good, only the count for the pagination is wrong also for the count on ( xtopics)

**Comment by rich20** [comment]
The unread topics shows correct, but the numbers of unread topics are wrong. Also if you click "Mark all read" remain the unread numbers the same. No matter which user are logged in. The number of "unread" is always the same.

**Comment by rich20** [comment]
The requested page can't be found.
Call to a member function order() on null

**Comment by rich20** [comment]
The requested page can't be found.
0 Call to a member function start() on null

**Comment by xillibit** [comment]
it's not possible i have removed the line with the order call...

**Comment by rich20** [comment]
The error is different now.

first
Call to a member function order() on null
now
0 Call to a member function **start()** on null

I've first tried with the patch tester. But also created a build with this fix. Both options show the same error.

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
The error is gone but now show "Unread" the same as the menu item Recent Topics

**Comment by rich20** [comment]
In principle it works correct now. But the count show the number of unread categories.

**Pull request merged**
