### PR TITLE
[K5.2] Remove old files from fancyBox v2.1.5 #7498

### LINKED ISSUE #7498: Remove old files from fancyBox v2.1.5
**Steps to reproduce the issue**
/components/com_kunena/template/crypsis/assets/css/fancybox.black-min.css
/components/com_kunena/template/crypsis/assets/css/fancybox.black.css
/components/com_kunena/template/crypsis/assets/css/fancybox.white-min.css
/components/com_kunena/template/crypsis/assets/css/fancybox.white.css

**Expected behavior**
You be removed on update

**Actual result**
You keep those old files after every update

**System information (please complete the following information)**
Joomla version: 3.9.21
Kunena version: 5.1.19
PHP version: 7.4.9
Database version: MySQL 5.7.31

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #7498.

Close #7498 
 
#### Testing Instructions

### CODE REVIEW

**Comment by xillibit** [comment]
@sshcli or @rich20 : do-you have tested it ?

**Comment by rich20** [comment]
> do-you have tested it ?

I think this is already fixed some time because these files do not exist anymore in K5.2. And if you update from K5.1 to K5.2 it removes the old css files also without this fix.

**Comment by rich20** [comment]
But what is with the other files which are listed to delete such as the rating.css, jssocials.css and so on?
These will be installed again in the folder assets/css.

**Comment by xillibit** [comment]
It's weird these files should be installed under /media/kunena/core/css and not anymore in /template/assets/css since this change :  https://github.com/Kunena/Kunena-Forum/commit/fd00f469734b578d1cb871f8d8decfef03701d25

**Comment by rich20** [comment]
> It's weird these files should be installed under /media/kunena/core/css and not anymore in /template/assets/css since this change : fd00f46

Yes I know, but these files will be installed still in the old path.
If you remove the css files manually, are these files again in /assets/css after installing K5.2 (not in /media/kunena...)

**Comment by xillibit** [comment]
I had forgot to remove some CCS files under assets\css and put them under core\css : https://github.com/Kunena/Kunena-Forum/pull/7504

**Comment by rich20** [comment]
It seems, something is still wrong

**Content in /core/css**
bootstrap.datepicker.css
fancybox.css
fileupload.css
jquery.atwho.css
jquery.fileupload-ui.css
jssocials.css
jssocials-theme-classic.css
jssocials-theme-flat.css
jssocials-theme-minima.css
jssocials-theme-plain.css

**Content in /assets/css**
jssocials.css
jssocials-theme-classic.css
jssocials-theme-flat.css
jssocials-theme-minima.css
jssocials-theme-plain.css
rating.css
rating-min.css
wbbtheme.css
wbbtheme-min.css

**Comment by rich20** [comment]
Addition:
If you delete manually the files before upgrade you get only these 4 files in /assets/css
rating.css
rating-min.css
wbbtheme.css
wbbtheme-min.css
so it seems the delete process does not work properly

**Pull request merged**
