### PR TITLE
New setting to let choose if the subject of topic can be changed on replies

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Reply and Reply Topic - Success
- [ ] Quick Reply - Failed

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
#### Blue Eagle

- [x] at Reply and Reply Topic - Success
- [x] at Quick Reply - Success

#### Crypsis
- [x] at Reply and Reply Topic - Success
- [ ] at Quick Reply - Failed (Notice: Trying to get property of non-object in components/com_kunena/template/crypsis/layouts/message/edit/quickreply.php on line 77)

**Comment by xillibit** [comment]
Check now i have updated it

**Comment by rich20** [comment]
#### Blue Eagle

- [x] at Reply and Reply Topic - Title can not be changed
- [ ] Submit removed the title - Cannot save message: Subject is empty!
- [ ] at Quick Reply - Title can be changed in the first post

#### Crypsis
- [x] at Reply and Reply Topic - Title can not be changed
- [ ] Submit removed the title - Cannot save message: Subject is empty!
- [ ] at Quick Reply - Title can be changed in the first post

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
#### Blue Eagle

- [x] at Reply and Reply Topic - Title can not be changed
- [x] Reply and Reply Topic - Cannot save message: Subject is empty!
- [x] with Quick Reply - Title can be changed if you reply the first post
- [ ] Quick Reply - Cannot save message: Subject is empty!

#### Crypsis
- [x] at Reply and Reply Topic - Title can not be changed
- [x] Reply and Reply Topic - Cannot save message: Subject is empty!
- [x] with Quick Reply - Title can be changed if you reply the first post
- [ ] Quick Reply - Cannot save message: Subject is empty!

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
#### Blue Eagle
- [x] Title can not be changed
- [x] Reply and Reply Topic - Cannot save message: Subject is empty!
- [x] with Quick Reply - Title can be changed if you reply the first post
- [x] Quick Reply - Cannot save message: Subject is empty!

#### Crypsis
- [x] Title can not be changed
- [x] Reply and Reply Topic - Cannot save message: Subject is empty!
- [x] with Quick Reply - Title can be changed if you reply the first post
- [x] Quick Reply - Cannot save message: Subject is empty!

**Pull request merged**
