### PR TITLE
Fix: dashboard trash button didn't work anymore

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #9655 . 
 
#### Summary of Changes
dashboard ison for trash was still pointing to old (removed) trash view
 
#### Testing Instructions
implement PR and click on the dasboard trash button, the trashs view should show without errors

### CODE REVIEW

**Comment by rich20** [comment]
I still get the same error message

**Comment by Ruud68** [comment]
The only thing this PR does is add an _s_ to the link, so first it was `..&view=trash` and now it is `..&view=trashs`

Can you check on if the link in your test site is correct, if not then I think the PR is not applied correct as I have tested this and for it now works correct

**Comment by rich20** [comment]
The "s" at the end is still missing. But I have noticed if I delete the complete file in the folder cpanel, it is no longer in the folder also after a new installation. This will not installed.

**Comment by Ruud68** [comment]
I just build an installation package with my PR branche.
Deleted the tml/cpanel directory (confirmed that the dashborad wasn't working due to mussing files) and installed the package: Installed without errors and dashboard with trash**s** is working correct
So guess there must be another issue on your server?

**Comment by rich20** [comment]
Yes, now it works for me too, after I emptied the cpanel folder on my server installation. Then I installed your PR again. 
I can't say what exactly the reason was, but I only realised after some time that the cpanel default.php was never updated during the installation.
Now the cpanel folder is empty and it still works.
Can be merged

**Pull request merged**
