### PR TITLE
Fix: access filter + anonymous yes/no

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #9649
 
#### Summary of Changes 
in category view:
- fixed accesslevel filter
- renames anonymous filter options to yes/no

#### Testing Instructions
@rich20

### CODE REVIEW

**Comment by rich20** [comment]
Yes, it now works in exactly the same way as in the category filter, the parent category must be selected. This is also how it works with the other filters.
The only filter that doesn't work at all now is the Select Access filter.

**Comment by Ruud68** [comment]
@rich20 the access filter should be fixed with this PR?

**Comment by rich20** [comment]
Addendum:
The text Yes/No is now correct. Can be merged.

**Comment by rich20** [comment]
> @rich20 the access filter should be fixed with this PR?v

No, it was just a general summary. Sorry!

The text error in the Anonymous filter has been fixed, so this PR can be merged.

**Pull request merged**
