### PR TITLE
Remove last usage of deprecated CKunenaUpload class

### PR DESCRIPTION
**Pull request by xillibit**
This affect only attachments upload under blue eagle template

### CODE REVIEW

**Comment by 810** [comment]
Doesn't blue eagle need this?

**Comment by xillibit** [comment]
I have replaced the code to don't use that deprecated class, blue eagle used this but not directly

**Comment by 810** [comment]
3rt party template still need this class. So we can't delete it yet

**Comment by xillibit** [comment]
it was used in attachements class so it doesn't affect others templates

**Comment by 810** [comment]
ok, then I will merge this one

**Pull request merged**
