### PR TITLE
Include whatsapp in profile Information #5471

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5471.

### CODE REVIEW

**Comment by rich20** [comment]
https://github.com/Kunena/Kunena-Forum/pull/5478/commits/f8806c9767927a536715a5e253c365b04ac40e98#diff-61f0ecd63231bba86f727ff793a8f0aa
kunena.install.upgrade.xml line 746 it lacks the end tag

**Comment by rich20** [comment]
- [x] Success

**Comment by rich20** [comment]
Whatsapp should also added in the backend. "Kunena -> Users -> User name ->tab User Info"

**Comment by xillibit** [comment]
Should be ok now

**Pull request merged**
