### PR TITLE
Change: refactor captcha implementation

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue # . 
 
#### Summary of Changes
refactored the captcha implementation: it is now controlled via:
- the new event triggering system
- global site config configured captcha (instead of calling all captchaś and take first response)

Also did some changes on the display (position) of the captcha in various places where the captcha is displayed

Also removed the name="submit" from the form's submit input field > this is a technical reason: every form has a submit function with which you can programmatically (via JS) submit the form, e.g. form.submit() bit when the form has an element with a name of "submit" then this element masks that function and as such that function cannot be called again leading to potential strange behavior.
 
#### Testing Instructions
test topc / message creation / responndign with different capctha's and see if it still works correct.

### CODE REVIEW

**Comment by rich20** [comment]
I get this error:
Class "ScssPhp\ScssPhp\Compiler" not found 

() 	JROOT/libraries/kunena/src/Template/KunenaTemplate.php:1655
2 	Kunena\Forum\Libraries\Template\KunenaTemplate->compileScss() 	JROOT/libraries/kunena/src/Template/KunenaTemplate.php:878
3 	Kunena\Forum\Libraries\Template\KunenaTemplate->createCacheDir() 	JROOT/components/com_kunena/template/aurelia/template.php:130
4 	KunenaTemplateAurelia->initialize() 	JROOT/libraries/kunena/src/Controller/Application/Display.php:244
5 	Kunena\Forum\Libraries\Controller\Application\Display->before() 	JROOT/libraries/kunena/src/Controller/Application/Display.php:102
6 	Kunena\Forum\Libraries\Controller\Application\Display->execute() 	JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:100
7 	Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
8 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/SiteApplication.php:218
9 	Joomla\CMS\Application\SiteApplication->dispatch() 	JROOT/libraries/src/Application/SiteApplication.php:261
10 	Joomla\CMS\Application\SiteApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:306
11 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/includes/app.php:58
12 	require_once() 	JROOT/index.php:32

**Comment by Ruud68** [comment]
can you build a 6.3 version without my PR in it? I don't think this is related to my PR but that 6.3 itself is not fully working correct?

@xillibit I think 6.3 is not based on the K6.2.2 yet. in 6.2 the namespace for the compiler is: KunenaScssPhp\ScssPhp\Compiler;

where in 6.3 this name space is ScssPhp\ScssPhp\Compiler

**Comment by xillibit** [comment]
Because i haven't merged the changes from K6.2 since i have created the K6.3 after the 20 october. So i need to merge your branch before that else there will be conflicts

**Comment by Ruud68** [comment]
Okay, so we have to wait then with testing. On my test environment it is not an issue as I do not have any css things that need to be compiled, so the error is not there for me.

**Comment by xillibit** [comment]
@rich20 : you can re-test now i have just merged the change from K6.2 tp avoid the error that you have

**Comment by rich20** [comment]
I tested it with:
CAPTCHA - Invisible reCAPTCHA
plg_captcha_recaptcha
Captcha - reCAPTCHA v3
(tested without key)
It seems to work, but I can only recognise it by the following changes.

If CAPTCHA - Invisible reCAPTCHA is selected - Captcha symbol is displayed
If plg_captcha_recaptcha is selected - Recaptcha Error no public key
If Captcha - reCAPTCHA v3 is selected - nothing is displayed

It can therefore be assumed that the selection works.

**Comment by Ruud68** [comment]
hi @rich20 thanks for testing! when selecting recaptcha v3 as your captcha plugin, you can see if it is at least loading the recapctha JS files in your browser tab.

If you want I can also mail you my own captcha plugin to test with (let me know if you want this) and where to send it to), but I feel confident that if the plugins you have used are working then it works correct and should work for all Joomla captcha plugins.

**Comment by rich20** [comment]
On this browser tab there is neither a script nor an error message regarding this captcha. I can only notice that this one captcha is not displayed. It works with the other two.
I can also test it with your captcha if you send it to me at rich@*kunena.org please.

**Comment by rich20** [comment]
@Ruud68 Can you please check this? Your captcha is not displayed anywhere, also not in the Joomla registration form.

**Comment by Ruud68** [comment]
Good morning, offline today so quick reply via mobile.
Plugin is enabled?
Plugin is configured to 'display' (first tab)
Plugin is selected in site global config?
Have it working myself on multiple sites myself, no issues.
If it still doesn't work, I can look into it tomorrow at the earliest

**Comment by rich20** [comment]
Sorry, I was completely off track. All works as it should and can be merged.

**Comment by Ruud68** [comment]
Thanks for reporting back @rich20 , must admit that you scared me a little, days before the release of this plugin :)
BTW, when you enable debug on the captcha plugin you can see in the plugin log file if it is actually working / responding to the captcha etc.

**Comment by Ruud68** [comment]
Add fix for #9597

**Comment by rich20** [comment]
- [x] Success - the "Deprecated" error is gone now

**Pull request merged**
