### PR TITLE
Feature: ajax upload for avatar #3885 (Part 2)

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by 810** [comment]
error: You can only add one avatar into your profile.

better is to overwrite the avatar

**Comment by xillibit** [comment]
It's normal because you can only add one avatar, you need to click on remove and choose an another one

**Comment by 810** [comment]
on the old behavior, the avatar was overwritten.

**Comment by xillibit** [comment]
So i don't keep the remove button and when choose a new avatar it overwritten the old one ?

**Comment by 810** [comment]
Keep the delete button, to switch back to default avatar, but upload always allow if req (size) are right.

**Comment by rich20** [comment]
- [x] Avatar upload - Success

Is the avatar galery obsolete now? You can't add images from the avatar galery.

**Comment by 810** [comment]
we should keep the gallery

**Comment by xillibit** [comment]
For the gallery i will look in a second time

**Pull request merged**
