### PR TITLE
 [K4.0] Max Links in message will divided by three if you insert a image

### PR DESCRIPTION
**Pull request by xillibit**
link #3318

### CODE REVIEW

**Comment by 810** [comment]
The function is twice in the file. So you need to edit it to

**Comment by xillibit** [comment]
The method checkMaxLinks() is only present one time in the file, i had defined this method to avoid duplicate code

**Comment by 810** [comment]
now you can always unlimited embed images

**Comment by xillibit** [comment]
Try now i may have done a mistake before

**Comment by 810** [comment]
again divided by three

**Comment by xillibit** [comment]
try now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
