### PR TITLE
Attachments: Insert all, set all attach as inserted

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by sshcli** [comment]
I still see the problem in  K.5.0.4-dev 2016-10-27

attach

**Comment by 810** [comment]
maybe only pictures are inserted, will check the files

**Comment by 810** [comment]
for me its working:
twea

**Comment by sshcli** [comment]
Or maybe the problem is nightly builds using old builds

**Comment by 810** [comment]
try clean cache and check that the code has changed.

**Comment by sshcli** [comment]
Working now after clean cache

good

**Pull request merged**
