### PR TITLE
Replace usage of checkDatabaseError() by exception in backend

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by 810** [comment]
why 5.1 not 5.0.1?

**Comment by xillibit** [comment]
I thought it was deprecated in Joomla! 4.0 but it's deprecated too in Platform 13.3

P.S.: you can merge this one, i will re-do something for 5.0.1 and i haven't replaced all checkDatabaseError()

**Comment by 810** [comment]
i meant why wait for Kunena 5.1 to merge not, already in K5.0.X branch

**Comment by xillibit** [comment]
I will close this one and re-do against k5.0.1 when the stable is out

**Pull request closed without merging**
