### PR TITLE
[K4.0] Crypsis: The Plugin Captcha - ReCaptcha (version 2.0) does not work with Kunena #3098

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
Error
Incorrect captcha. Please try again.

**Comment by xillibit** [comment]
@rich20 : you can try now, i have updated it

**Comment by 810** [comment]
Fatal Error: Can't use method return value in write context in components/com_kunena/controllers/topic.php on line 346

**Comment by 810** [comment]
I Get a notice on phpstorm  that's only working on php >= 5.5

**Comment by xillibit** [comment]
try now you shouldn't have the fatal error

**Comment by 810** [comment]
- [x] When reply with captcha
- [ ] When reply without captcha - error: Fatal Error: Call to a member function getError() on a non-object in components/com_kunena/controllers/topic.php on line 360

**Comment by rich20** [comment]
I've additional problems. The captcha appears fully ineffective.
With Chromium you need only mark checkbox and then submit.
bildschirmfoto vom 2015-05-20 17 55 36
With Firefox it does not matter if you choose wrong images. You can submit.
bildschirmfoto vom 2015-05-20 18 05 40

**Comment by xillibit** [comment]
> When reply without captcha - error: Fatal Error: Call to a member function getError() on a non-object in components/com_kunena/controllers/topic.php on line 360

I will remove that part for now, but i need to find a way to display the error message if needed

**Comment by Ruud68** [comment]
Hi, just added the changes to the files in this commit manually on Kunena 4.0 RC1 and now the captcha 2.0 works > both on new reply as on new topic! :+1:

**Comment by xillibit** [comment]
Thanks to confirm that it works

**Pull request merged**
