### PR TITLE
Error message not visible on drag and drop #5288

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5288.

### CODE REVIEW

**Comment by sshcli** [comment]
I have tested now, and I can't see the difference

**Comment by 810** [comment]
remove the fix, and add this to line 252
`$('#kattach_form').show();`

**Comment by xillibit** [comment]
If you do a drag&drop, it show the form, in this case it's work if the file size is above the limit set in confiuration, i will add the change suggested by jelle to make it working in all cases

**Comment by sshcli** [comment]
it works for me now.
but only when moving code to line 252

**Comment by xillibit** [comment]
Try now

**Comment by sshcli** [comment]
**Test results** = Success ✔

**Pull request merged**
