### PR TITLE
[K5.1] B3 | Quick reply data not copied when going full editor #6233

### LINKED ISSUE #6233: Crypsis b3 | Quick reply content not preserved when switching to full editor
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/157353-quick-reply-content-not-preserved-when-switching-to-full-editor

This issue seems only for Crypsis fixed, but not for Crypsis b3. (I can't find a commit here for this question)

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #6233. 

Close #6233
 
#### Testing Instructions

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Quick reply default - Success
- [x] Quick reply modal - Success
- [ ] Quick reply always visible - Failed | **With this option it also not work with Crypsis**

**Comment by xillibit** [comment]
>     * Quick reply always visible - Failed | **With this option it also not work with Crypsis**

When do-you find this setting ?

**Comment by rich20** [comment]
You find this in the template setting (tab Advanced)
Also on k.org is the quick reply field always open below the last message of a topic.

**Comment by xillibit** [comment]
try now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
