### PR TITLE
[develop] [4.0] Category moderators are displayed as moderator in all

### PR DESCRIPTION
**Pull request by xillibit**
categories #2950

### CODE REVIEW

**Comment by rich20** [comment]
#### Crypsis:
- [x] Index Page - Success
- [x] The profile infos beside the messages - Success
- [ ] Profile - (he is displayed as Moderator)
- [ ] Recent Topics - (Username has moderator color in all categories)
- [ ] Recent Posts - (Username has moderator color in all categories)

#### Blue Eagle:
- [ ] Profile - (he is displayed as Moderator)
- [ ] (Username has moderator color everywhere)

**Comment by xillibit** [comment]
With crypsis all should be good, i need to apply the fix under crypsis b3 too...

**Comment by xillibit** [comment]
I have applied the fix to crypsis b3 too and with blue eagle it should work too

**Comment by rich20** [comment]
#### Crypsis:
- [x] Index Page - Success
- [x] The profile infos beside the messages - Success
- [ ] Profile - He is displayed as Moderator
- [ ] Recent Topics - Username has moderator color left if he is topic author
- [ ] Recent Posts - Username has moderator color left if he is topic author
bildschirmfoto vom 2015-06-14 16 52 37

**Comment by rich20** [comment]
Addition:
Notice: Undefined variable: category in components/com_kunena/template/blue_eagle/html/topics/default_row.php on line 99

**Comment by xillibit** [comment]
I have updated it

> Profile - He is displayed as Moderator

For that it will stay like that

**Comment by rich20** [comment]
#### Crypsis:
- [x] Everything - Success

#### Blue Eagle:
- [ ]  Recent Topics - Username has moderator color left if he is topic author
- [ ] The profile infos beside the messages - User has moderator color in all topics

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Recent Topics - Username has moderator color left if he is topic author
- [ ] The profile infos beside the messages - User has moderator color in all topics
- [ ] Index - User has moderator color in all categories

**Comment by rich20** [comment]
I see now there are more places where username has moderator color
#### Crypsis
- [ ] In single categories - Username has moderator color
- [ ] In single categories - Username has moderator color left if he is topic author
- [ ] My Topics - Username has moderator color in all topics

#### Blue Eagle
- [ ] The profile infos beside the messages - User has moderator color in all topics
- [ ] Index - User has moderator color in all categories
- [ ] In single categories - Username has moderator color
- [ ] In single categories - Username has moderator color left if he is topic author
- [ ] My Topics - Username has moderator color in all topics
- [ ] My Topics - Username has moderator color left if he is topic author

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
#### Crypsis
- [x] In single categories - Username has moderator color
- [x] In single categories - Username has moderator color left if he is topic author
- [x] My Topics - Username has moderator color in all topics

#### Blue Eagle
- [x] In single categories - Username has moderator color
- [x] In single categories - Username has moderator color left if he is topic author
- [x] My Topics - Username has moderator color in all topics
- [x] My Topics - Username has moderator color left if he is topic author

- [ ] The profile infos beside the messages - User has moderator color in all topics
- [ ] Index . Fatal Error
Fatal Error: Call to a member function getCategory() on null in components/com_kunena/template/blue_eagle/html/category/list_embed.php on line 125

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
This seems now all ok. Only in search results the username has moderator color in all categories.
With Crypsis as well as Blue Eagle.

**Comment by xillibit** [comment]
I've modified for search in blue eagle and crypsis

**Comment by rich20** [comment]
- [x] Now is all ok with Crypsis as well as Blue Eagle

**Pull request merged**
