### PR TITLE
Attachment upload broken since changes on correctimageorientation method

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # . 
 
#### Testing Instructions

### CODE REVIEW

**Comment by rich20** [comment]
jpg and png image upload works, also image rotate is correct. But you can't upload other attachments such as .txt or .zip
Is this another bug or related to this bug here?

**Comment by rich20** [comment]
It shows this if you want upload a file:
Unable to get properties for the image.

**Comment by xillibit** [comment]
Maybe it's related, i have removed a check to test if jpeg

**Comment by xillibit** [comment]
Should works now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
