### PR TITLE
Change sticky topic icon to pushpin

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue https://github.com/Kunena/Kunena-Forum/issues/5083

### CODE REVIEW

**Comment by rich20** [comment]
Are two files. systemicons.xml and topicicons.xml

**Comment by sshcli** [comment]
I have closed this because there was a conflict with travis.
Maybe I skip something, I don't know.

@810 or @xillibit  Maybe you have a better way to fix this later.

Regards

**Comment by 810** [comment]
please reopen

**Comment by sshcli** [comment]
Can't reopen.
I have created a new PR https://github.com/Kunena/Kunena-Forum/pull/5100

**Comment by sshcli** [comment]
Ok, the new PR now pass the travis test and is ready to be merged.
Thanks

**Pull request closed without merging**
