### PR TITLE
Google icon does not have a link #5456

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #5456.

### CODE REVIEW

**Comment by mc-hovanskiy** [comment]
Please correct this way:
`' google ' => array ( ' url ' => 'https://plus.google.com/+## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_GOOGLE ' ), ' nourl ' => ' 0 ' ),`

`' vk ' => array ( ' url ' => ' https://vk.com/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_VK ' ), ' nourl ' => ' 0 ' ),`

`' telegram ' => array ( ' url ' => ' https://t.me/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_TELEGRAM ' ), ' nourl ' => ' 0 ' ),`

**Comment by mc-hovanskiy** [comment]
and Skype
`' skype ' => array ( ' url ' => ' skype:## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_SKYPE ' ), ' nourl ' => ' 0 ' ),`

**Comment by xillibit** [comment]
> Please correct this way:
> ' google ' => array ( ' url ' => 'https://plus.google.com/+## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_GOOGLE ' ), ' nourl ' => ' 0 ' ),
> 
> ' vk ' => array ( ' url ' => ' https://vk.com/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_VK ' ), ' nourl ' => ' 0 ' ),
> 
> ' telegram ' => array ( ' url ' => ' https://t.me/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_TELEGRAM ' ), ' nourl ' => ' 0 ' ),



> and Skype
> ' skype ' => array ( ' url ' => ' skype:## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_SKYPE ' ), ' nourl ' => ' 0 ' ),

The issue by doing that is that we need to add an update tool to convert the existing info in the profile, else users will have some issues

**Comment by xillibit** [comment]
I have updated it, no need to add an update tool

**Pull request merged**
