### PR TITLE
Confidential is showed on email #3606

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
Remove confidential on email
- [ ] Blue eagle - failed
- [ ] Crypsis - failed

**Comment by rich20** [comment]
Remove confidential on email
- [ ] Blue eagle - failed
- [ ] Crypsis - failed

**Comment by xillibit** [comment]
Should be better now

**Comment by 810** [comment]
No,

now admins can't see the confidential on the page. Also I still see the confidential on the normal users  email

**Comment by xillibit** [comment]
For me it's work correctly, the confidential are right displayed on messages but not in emails

**Comment by rich20** [comment]
> For me it's work correctly, the confidential are right displayed on messages but not in emails

For me it works also correctly on messages

**Comment by 810** [comment]
ok, works now

**Pull request merged**
