### PR TITLE
 Guest: New topic with attach not saved #3160

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
Fatal Error: Call to a member function authorise() on a non-object in components/com_kunena/controllers/topic.php on line 877

**Comment by 810** [comment]
missing line line 875:

````		$topic = KunenaForumTopicHelper::get($this->id); ````

Then attachments works, count works, and even topic icon works suddenly

**Comment by xillibit** [comment]
You have commented the wrong PR

**Comment by 810** [comment]
+1

**Pull request merged**
