### PR TITLE
Youtube video doesn't work because links aren't correct

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
only autoembedyoutube is working the video's from video tags are broken "This content cannot be displayed in a frame". And the video of the issue, you get "An error is occurred, please try again later"

**Comment by 810** [comment]
You can close this issue, because the user had a extra character in his url, so everything still works.

**Comment by xillibit** [comment]
If you put link into video brackets like that : [video]https://www.youtube.com/watch?v=bpk7ERlZ0CI[/video]  the video isn't displayed, but yes if put only link it works

**Comment by 810** [comment]
if you have only "[video width=425 height=344 type=youtube]bpk7ERlZ0CI[/video]" you get Cannot save message: Message body is empty!

**Comment by xillibit** [comment]
That's was an another issue, i don't find it anymore in issues list

**Comment by 810** [comment]
@test +1

**Comment by rich20** [comment]
> if you have only "[video width=425 height=344 type=youtube]bpk7ERlZ0CI[/video]" you get Cannot save message: Message body is empty!

It's the same with this bbCode :  [video]https://www.youtube.com/watch?v=bpk7ERlZ0CI[/video] 
Without text you cannot save videos. Enter a text and both code work.

**Comment by 810** [comment]
yeah that is a different issue, is the YouTube still working?

**Comment by rich20** [comment]
> yeah that is a different issue, is the YouTube still working?

- [x]  YouTube works

**Pull request merged**
