### PR TITLE
Nobody can see confidential text (also not admins) - but if you click on quote, all users can see it #3981

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by 810** [comment]
@rich20 could you test this one, also check if the confidential is removed on email.

**Comment by rich20** [comment]
- [x] Author, Admins and Moderators can see confidential texts
- [x] E-Mail - No confidential informations
- [ ] With quote button all users can see it

**Comment by 810** [comment]
the other issue, is also on K4.0 and other versions

**Comment by 810** [comment]
Please create a new ticket for that issue. I'm merging this pr

**Pull request merged**
