### PR TITLE
[3.1] Report to moderator: Reported post is the first message #2725

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
Blue Eagle e-mail contains
- [x] Reported MessageID - Success
- [x] Report Sender - Success
- [x] Report Reason - Success
- [x] Report Message - Success
- [x] Message Poster - Success
- [x] Message Subject - Success
- [x] Message - Succss

Crypsis e-mail contains
- [x] Reported MessageID - Success
- [x] Report Sender - Success
- [x] Report Reason - Success
- [x] Report Message - Success
- [x] Message Poster - Success
- [x] Message Subject - Success
- [ ] Message - Empty (only lines)

**Comment by xillibit** [comment]
> Message - Empty (only lines)

What you mean ?

**Comment by rich20** [comment]
Here is the content fom the Crypsis mail: 

Report Sender: richi (richard)
Report Reason: test
Report Message: report

Message Poster: richi (richard)
Message Subject:: Welcome to Kunena!

Message:
-----
...
-----

**Comment by 810** [comment]
+1 All is working

**Comment by 810** [comment]
Please change it to "$this->numLink" , also on the mail.

**Comment by xillibit** [comment]
@810 : you can re-check it the link in the email should at the right message in the topic

**Comment by 810** [comment]
nope, only to the right page, but not to the topic.

if i have the option: 
- [x] Reply Numbering Inside Topic "real id"

**Comment by xillibit** [comment]
Try now it should be ok

**Comment by 810** [comment]
- [x] Reply Numbering Inside Topic "real id" 
- [x] Reply Numbering Inside Topic "message id" 
- [ ] bottom position
- [ ] top position

**Comment by rich20** [comment]
Crypsis and Joomla 3.3.6
- [x] Reported MessageID - Success
- [x] Message content - Success

Crpsis and Joomla 3.4.0 DEV as well as Joomla 3.4.0 alpha
- [x] Reported MessageID - Success
- [ ] Message content - Empty

**Comment by 810** [comment]
im closing this pr, #2743 will fix the issue's

**Pull request closed without merging**
