### PR TITLE
Show in quick reply, input to enter mail if it's required #3512  4.0 bug  (part2)

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by xillibit** [comment]
You have forgot to change on blue eagle, next time do a pull request on mine

**Comment by rich20** [comment]
Name field will displayed for all users (also admins) and fatal error when click Submit.

Fatal Error: Call to a member function isHtml() on null in components/com_kunena/template/crypsis/layouts/email/subscription/default.php on line 15

**Comment by 810** [comment]
@rich20 this is the new J35 bug: https://github.com/Kunena/Kunena-Forum/issues/3516

**Comment by rich20** [comment]
Ok, then remains the error with the name field.

**Comment by rich20** [comment]
- [x] Success

But why is closed this pr? With this fix is the fatal error resolved. https://github.com/Kunena/Kunena-Forum/pull/3513
Fatal Error: Call to a member function isHtml() on null in components/com_kunena/template/crypsis/layouts/email/subscription/default.php on line 15

**Comment by 810** [comment]
@rich20 because the bug wasn't in yet, but I fixed it last night. I will merge this one.
If you create a new build you will see that the errors are gone.

**Comment by Ruud68** [comment]
sorry for being #mia :) busy with new customer.
tested this (on crypsis) and it works correctly!
Thanks!

**Pull request merged**
