### PR TITLE
On Crypsis is missing the option category jump #3984

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #3984 .

### CODE REVIEW

**Comment by 810** [comment]
Rendering Error in layout Category/Index: Property "categorylist" is not defined in \components\com_kunena\template\crypsis\layouts\category\index\default.php on line 19
Layout was rendered in \libraries\kunena\controller\display.php on line 159

[14-Jun-2016 00:03:29 Europe/Amsterdam] PHP Notice:  Undefined property: ComponentKunenaControllerTopicListRecentDisplay::$ktemplate in \components\com_kunena\controller\topic\list\display.php on line 89

[14-Jun-2016 00:03:29 Europe/Amsterdam] PHP Notice:  Trying to get property of non-object in \components\com_kunena\controller\topic\list\display.php on line 89

Also change Crypsisb3

**Comment by xillibit** [comment]
Fixed

**Comment by 810** [comment]
when forumjump is disabled, you still see the list.

Also todo crypsisb3

**Comment by xillibit** [comment]
Updated, i will do for crypsis b3 in another PR

**Comment by rich20** [comment]
- [x] Success - The errors are gone now, but it lacks this option at topics (such as in Blue Eagle). Is this ok?

**Comment by xillibit** [comment]
In this case i will add too the option in topics like it was in blue eagle

**Comment by xillibit** [comment]
I have added too into the topic

**Pull request merged**
