### PR TITLE
 [K4.0] COM_KUNENA_POST_ATTACHMENTS_NOT_ALLOWED #3299

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Image Uploads = Nobody + File Uploads = Registered Users - Success
- [x] Image Uploads = Moderators + File Uploads = Registered Users - Success
- [ ] Image Uploads = Administrators + File Uploads = Registered Users - Failed (Posting attachments is allowed only for administrators)

- [x] File Uploads = Nobody + Image Uploads = Registered Users - Success
- [x] File Uploads = Moderators + Image Uploads = Registered Users - Success
- [ ] File Uploads = Administrators + Image Uploads = Registered Users - Failed (Posting attachments is allowed only for administrators)
- [ ] Only Crypsis - If you add non-permitted attachments, you can nevertheless Submit the message (it will saved without attachments)

**Comment by xillibit** [comment]
> Only Crypsis - If you add non-permitted attachments, you can nevertheless Submit the message (it will saved without attachments)

I don't understand the message is saved or not ?

**Comment by rich20** [comment]
#### Blue Eagle
- [x] Image Uploads = Nobody + File Uploads = Registered Users - Success
- [x] File Uploads = Nobody + Image Uploads = Registered Users - Success
- [x] Image Uploads = Moderators + File Uploads = Registered Users - Success
- [x] File Uploads = Moderators + Image Uploads = Registered Users - Success
- [x] Image Uploads = Administrators + File Uploads = Registered Users - Success
- [x] File Uploads = Administrators + Image Uploads = Registered Users - Success

#### Crypsis
- [ ] It's not possible to upload attachments (Authorization failed: Invalid action topic.post.attachment.create!)

> I don't understand the message is saved or not ?

The message is saved. But ignore it. I think, it has nothing to do with this issue here. It's a other problem.

**Comment by xillibit** [comment]
> The message is saved. But ignore it. I think, it has nothing to do with this issue here. It's a other problem.

In this case open an another issue for it

**Pull request merged**
