### PR TITLE
It lacks the option @import 'custom.less'; in the crypsis.less #5102

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by rich20** [comment]
- [ ] New installation - Failed  with Class 'KunenaTemplate' not found
- [ ] Upgrade - @import 'custom.less'; goes on the fist place in the crypsis.less (it should load as last file)

**Comment by 810** [comment]
try again

**Comment by rich20** [comment]
- [x] Upgrade - @import 'custom.less'; 
- [ ] New installation - Failed 
Warning: fopen(/www/.../components/com_kunena/template/crypsis/assets/less/custom.less): failed to open stream: No such file or directory in /www/...7/tmp/install_58505efb7e5e1/packages/install_58505efba8fbb/install/install.script.php on line 632
can't open file

**Comment by 810** [comment]
try again

**Comment by rich20** [comment]
- [x] Upgrade - @import 'custom.less'; 
- [ ] New installation - Failed (the same error)
Warning: fopen(/www/.../components/com_kunena/template/crypsis/assets/less/custom.less): failed to open stream: No such file or directory in /www/.../tmp/install_5850686f776ed/packages/install_5850686fa997f/install/install.script.php on line 632
can't open file

**Comment by 810** [comment]
next try

**Comment by rich20** [comment]
Strange, again the same error.

**Pull request merged**
