### PR TITLE
[develop]Crypsis: If you create a new topic the subject is already here #2902

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
the data isn't saved from quickreply to editor

**Comment by xillibit** [comment]
In which case it should be saved from quickrely to editor form ?

**Comment by 810** [comment]
untitled

**Comment by xillibit** [comment]
I will ask to the author of script because i don't know why it doesn't work in this case

**Comment by 810** [comment]
it worked now, but can we remove the 10 sec or change it to 1 sec.

Also we need clear data on cancel or close qreply

**Comment by xillibit** [comment]
I have updated the PR

> Also we need clear data on cancel or close qreply and on submit

On cancel or submit the data are already cleared automatically by the script

**Comment by 810** [comment]
Ok after testing, this works, should be
````
/* Store form data into localstorage for 2000 second */
	jQuery("#postform").sisyphus( {
			locationBased: false,
			timeout: 2000
	});
````

**Comment by xillibit** [comment]
Why the timeout on 2000 seconds ? So each every 2000 seconds the data are stored in browser storage so it's a long time

**Comment by 810** [comment]
I think the option is How long store data. When i set it to 2000, the data is stored.

**Comment by xillibit** [comment]
No :  ```timeout is an interval in seconds to perform saving data. If 0 - save on each time field is updated.```

**Comment by xillibit** [comment]
PR updated

**Comment by rich20** [comment]
Does not work. Go in your profile and empty the cache. Then try edit some message. The edit field will empty.

**Comment by xillibit** [comment]
Branch updated

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
