### PR TITLE
[K6.0] Blocked direct images pastes which result in data:image garbage in the message text

### PR DESCRIPTION
**Pull request by c-schmitz**
Pull Request for Issue #9475 
 
#### Summary of Changes 
Added a small plugin to CKEditor that disallow direct pasting of image data to prevent garbage.
 
#### Testing Instructions
See issue #9475 - now when trying to paste such an image a message will be shown and the paste will be blocked.

### CODE REVIEW

**Comment by rich20** [comment]
Does it work for you? Although the plugin will installed, I can copy an image from a folder and paste it.

**System information**
- Joomla version: 4.2.9-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.10-DEV
- Kunena template: Aurelia
- Php version: 8.0.26
- Database version: 10.5.18-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by c-schmitz** [comment]
Yeah, after clearing my cache it works just fine.

**Comment by c-schmitz** [comment]
You can check it on forums.limesurvey.org.

**Comment by xillibit** [comment]
Works only on edge 111.0 not on firefox 111.0

**Comment by c-schmitz** [comment]
Works for me fine on Firefox 111 (Windows). (I am only using Firefox).

**Comment by c-schmitz** [comment]
Any chance this getting merged for next release? ;)

**Comment by xillibit** [comment]
So, can-you resolve the conflict please ?

**Pull request merged**
