### PR TITLE
Add desc and maxlength to description field (backend)

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue # .
#### Summary of Changes

Add a description to description field (backend)
Add  maxlength=140 to description field (backend)

desc

### CODE REVIEW

**Comment by 810** [comment]
Why max 140 ?

**Comment by sshcli** [comment]
That's what you have defined here:
src\components\com_kunena\controller\category\topics\display.php

**Comment by 810** [comment]
Thats the value for showing the first 140 characters, if more then the rest will be changed to ...

**Comment by sshcli** [comment]
Ok.
What do you suggest?
Remove maxlength=140 and leave only description?

**Comment by 810** [comment]
yes, and remove the (max 140 char) text

**Pull request merged**
