### PR TITLE
Rendering Error in layout Topic/List #4101

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #4101  .

### CODE REVIEW

**Comment by 810** [comment]
I think you need to do it also on the crypsisb3 file

**Comment by rich20** [comment]
> I think you need to do it also on the crypsisb3 file

Yes, with Crypsisb3 the error still exists with a little difference of the lines.

Tab subscriptions:
Rendering Error in layout Topic/List: Property "categorylist" is not defined in /components/com_kunena/template/crypsisb3/layouts/topic/list/default.php on line 44
Layout was rendered in /components/com_kunena/template/crypsisb3/layouts/user/item/default.php on line 13

Tab favorites:
Rendering Error in layout Topic/List: Property "categorylist" is not defined in /components/com_kunena/template/crypsisb3/layouts/topic/list/default.php on line 44
Layout was rendered in /libraries/kunena/layout/base.php on line 183
- [x] With Crypsis - Success

**Comment by xillibit** [comment]
Changed too into crypsis b3

**Comment by rich20** [comment]
- [x] with Crypsis
- [x] with Crypsisb3

**Pull request merged**
