### PR TITLE
[develop] [4.0] Category moderators are displayed as moderator in all categories #2950

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
ranks is good now, only the users have still the blue color

**Comment by xillibit** [comment]
@rich20 : is-ti ok for you ?

**Comment by rich20** [comment]
> ranks is good now, only the users have still the blue color

It's not ok.The username is still in all categories 
#kunena.layout .kwho-moderator {
    color: #0000ff !important;
}

**Comment by xillibit** [comment]
try now

**Comment by rich20** [comment]
- [x] Rank at the message view - Success
- [x] User color at the message view - Success
- [ ] Rank in the Profile - Failed (he is displayed as moderator)
- [ ] On all Index, Recent Topics and Recent Posts, it shows with moderator color  -  I'm not sure whether it's correctly (but it's the same like in K 3.0)

**Comment by xillibit** [comment]
> Rank in the Profile - Failed (he is displayed as moderator)

In profil there isn't category so you can't set others rank image

**Comment by rich20** [comment]
In blue eagle 3.0 category moderator is displayed as a normal user in his profile

**Comment by xillibit** [comment]
For profile, it's the same between blue eagle and crypsis:

profle

**Comment by rich20** [comment]
> For profile, it's the same between blue eagle and crypsis:

Yes, that's correct. I've only noticed, it's a difference between K 3.0
g3028

**Comment by xillibit** [comment]
I will merge as it because i'am not sure how to fix in profile and recent discussions

**Pull request merged**
