### PR TITLE
Database error on User Synchronization #6339

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue #6339. 
 
#### Testing Instructions

### CODE REVIEW

**Comment by rich20** [comment]
> There are two different errors on User Synchronization

The second error is solved, but the first error is still there

- [ ] **Mark Remove user profiles from deleted users**
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `a` LEFT JOIN `rich_users` AS `b`ON a.userid=b.id WHERE b.username IS NULL' at line 2

- [x] **Mark Delete lifetime ban users**
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `a` LEFT JOIN `rich_users` AS `b`ON a.userid=b.id WHERE banned='1000-01-01 00' at line 2

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
Now we have an error on the others option again
- [x] **Mark Remove user profiles from deleted users**
- [ ] **Mark Delete lifetime ban users**  | Error - Query was empty

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
