### PR TITLE
[K4.0] Blue eagle search results: images not parsed. #3121

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
Warning: Missing argument 3 for KunenaView::parse(), called in C:\wamp\www\clean\components\com_kunena\views\search\view.html.php on line 155 and defined in libraries/kunena/view.php on line 285

**Comment by xillibit** [comment]
Where do-you get this error ?

**Comment by 810** [comment]
untitled

**Comment by 810** [comment]
oh my fault, I edit the github dir, not local, but now I have this issue

untitled

**Comment by xillibit** [comment]
I don't have neither this issue : 

fghjklhgre

**Comment by rich20** [comment]
For me, it works without error.
@810 Why you have highlight search result? You have tested the same build?

**Comment by 810** [comment]
yes, my highlight pr, breaks the line.

**Pull request merged**
