### PR TITLE
Trigger Joomla! captcha plugin in crypsis template

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by 810** [comment]
code works, but when you do another reply/new topic, the captcha is not there, and you still see the text;
"Enter code here"

**Comment by xillibit** [comment]
When i try, the captcha appears each time for new topic or reply

**Comment by rich20** [comment]
- [x] Reply - Success
- [x] Reply Topic - Success
- [x] New Topic - Success
- [ ] Quick Reply - Failed (it works only on the first message in pages)

**Comment by xillibit** [comment]
With Crypsis all the captcha settings need to be set under the plugin recaptcha

**Comment by rich20** [comment]
Ok, then remains only the Quick Reply bug.

**Comment by xillibit** [comment]
I removed button quick reply when you are guest, the plugin captcha from doesn't handle multiple instances of captcha in same page

**Comment by rich20** [comment]
- [x] Reply - Success
- [x] Reply Topic - Success
- [x] New Topic - Success
- [x] Quick Reply hide for guests - Success
- [ ] Quick Reply and CAPTCHA Challenge for Users - Failed (it works only on the first message in pages)

**Comment by xillibit** [comment]
Quick reply should'nt appear for guests, so it still appear when you are you a guest ?

**Comment by rich20** [comment]
You find this option in Kunena Security setting > CAPTCHA Configuration > CAPTCHA Challenge for Users

**Comment by rich20** [comment]
> Quick reply should'nt appear for guests, so it still appear when you are you a guest ?

For guests it is ok, but you can also choose Captcha for registered users. And for registered users exists the quick reply.

**Comment by xillibit** [comment]
You can try now

**Comment by rich20** [comment]
When click on Reply:

Fatal Error: Call to undefined method KunenaForumCategory::canDoCaptcha() in components/com_kunena/controller/topic/form/reply/display.php on line 59

**Comment by xillibit** [comment]
You can try now

**Comment by rich20** [comment]
Now have guests the buttons Reply and also Quick Reply
Registered users have only the Reply button
Captcha is not displayed

**Comment by xillibit** [comment]
Should be better now

**Comment by rich20** [comment]
- [x] Captcha for guests - Success
- [ ] CAPTCHA Challenge for Users - Failed (Captcha is not displayed for registered users)
- [ ] Nobody see the Quick Reply (also not admins)

**Comment by xillibit** [comment]
You can see quick reply button if you disable catpcha plugin, only guests can see captcha the followings settings are for legacy purpose : 

catpcha_legacy

**Comment by rich20** [comment]
Try CAPTCHA Challenge for Users = 1 (or more) and nobody see the Quick Reply.

**Comment by rich20** [comment]
Addition:
Sorry, you're right. But when the captcha plugin must be disabled, the user can use captcha in Joomla?

**Comment by rich20** [comment]
### Summary:
### If the plugin is disabled
- [x] Quick Reply works

### If the plugin is enabled
- [x]  Captcha for guests - Success
- [ ] Nobody can see the Quick Reply button
- [ ]  CAPTCHA Challenge for Users - Failed (Captcha is not displayed for registered users)

**Comment by xillibit** [comment]
I have tried with blue eagle with the following settting:
dfdffg

For registred users they have captcha but not access to quick reply button but mods and admins have access to quick reply

**Comment by xillibit** [comment]
I have updated it: 

-If captcha plugin is enabled nobody can see quick reply button excepts admin/mods
-Registred users can see catpcha if the two followings settings are enabled: 

dfdffg

**Comment by rich20** [comment]
### If the plugin is disabled
- [x] Quick Reply works - Success
- [x] Nobody needs captcha - Success

### If the plugin is enabled
- [ ]  CAPTCHA Challenge for Users - Failed (If you set additional CAPTCHA Challenge for Guests = Yes (Captcha is not displayed for registered users))

> If captcha plugin is enabled nobody can see quick reply button excepts admin/mods

Not optimal. When a user has reached the captcha limit, he has not the button Quick Reply.

**Comment by xillibit** [comment]
> (If you set additional CAPTCHA Challenge for Guests = Yes (Captcha is not displayed for registered users))

You should set to No if you want that the captcha will be displayed for registred users, if you set to Yes it for guests...

**Comment by xillibit** [comment]
> Not optimal. When a user has reached the captcha limit, he has not the button Quick Reply (such as with Blue Eagle).

I changed it to check against user posts to show if it under the limit

**Comment by rich20** [comment]
> I changed it to check against user posts to show captcha if it under the limit

In principle it works, but not exactly. If you set limit 8 then is the tenth post without captcha. It's 1 post more as the limit. Quick Reply is nevertheless not present.

> (If you set additional CAPTCHA Challenge for Guests = Yes (Captcha is not displayed for registered users))

>>  You should set to No if you want that the captcha will be displayed for registred users, if you set to Yes it's for guests...

That's not right. If a admin want only captcha for his registered users it's ok. But what is, if he wants additional also a category for guests? He can only use the captcha either for users or guests. Not for both.

#### Summary

- [ ] Captcha limit is not exact (it's 1 post more as the limit)
- [ ] Quick Reply (when a user has reached the captcha limit, he has not the button Quick Reply)
- [ ] Captcha for both (user and guests) is not possible

**Comment by xillibit** [comment]
> Captcha limit is not exact (it's 1 post more as the limit)

When the user has 3 posts and the limit is set to 3 the captcha is showed, when the user reply it can't see the captcha

> Quick Reply (when a user has reached the captcha limit, he has not the button Quick Reply)

Fixed

> Captcha for both (user and guests) is not possible

It works like that on blue eagle

**Comment by rich20** [comment]
< When the user has 3 posts and the limit is set to 3 the captcha is showed, when the user reply it can't see the captcha, i don't see the issue here

If the limit is set to 3, the captcha will be shown also at post 4

> Captcha for both (user and guests) is not possible
>> It works like that on blue eagle

No, in blue eagle you can use both at the same time

- [ ] Quick Reply - Failed (it is now always visible, even if the limit is not reached)

**Comment by rich20** [comment]
#### Addition

The quick reply fix works. But only then, if you choose additional Captcha for Guests = Yes. But then shows the captcha not for users.

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x]  All works correct now :+1:

**Pull request merged**
