### PR TITLE
Fix mb_substr on subject titles

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by mahagr** [comment]
mb isn't installed to all Joomla sites. Joomla has its own JText class for this.

**Comment by 810** [comment]
I can't see any substr code their.

**Comment by mahagr** [comment]
Yea, could be. Still you cannot use it. Maybe use preg_replace with `'/.{0,' . $limit . '}/|ui'` instead?

**Comment by 810** [comment]
That didn't work, found a other fix

**Comment by mahagr** [comment]
Do not add code to template files. create a function into kunena instead...

**Comment by 810** [comment]
moved the files

**Pull request merged**
