### PR TITLE
When deleting attachment in backend update topic object #2387

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
- [x] Success (it remains only the code in messages "Attachment not found")

The topic should also be updated, if you delete attachments in User-Profile Attachment Manager.

**Comment by xillibit** [comment]
I haven't check the message i think i need to update it

**Comment by xillibit** [comment]
You can try noow for backend and profile should be good

**Comment by rich20** [comment]
- [x] Delete in backend - Success 
- [x] Delete in user profile - Success 

(It remains only the code in messages "Attachment not found")

**Comment by 810** [comment]
that's a other issue, you need to recount by yourself. Merging this one

**Pull request merged**
