### PR TITLE
Show in quick reply, input to enter mail if it's required #3512

### PR DESCRIPTION
**Pull request by xillibit**
See issue : https://github.com/Kunena/Kunena-Forum/issues/3512

### CODE REVIEW

**Comment by Ruud68** [comment]
Hi @xillibit , just tested your code and it is not working (condition syntax was wrong).
did some changes myself and this is what I came up with to make it work:

``` php
            <?php if ($config->askemail && !$user->id) : ?>
            <div class="controls">
                <input type="text" id="email" name="email" size="35" placeholder="<?php echo JText::_('COM_KUNENA_TOPIC_EDIT_PLACEHOLDER_EMAIL') ?>" class="inputbox" maxlength="35" value="" required />
                <?php echo $config->showemail == '0' ? JText::_('COM_KUNENA_POST_EMAIL_NEVER') : JText::_('COM_KUNENA_POST_EMAIL_REGISTERED'); ?>
            </div>
            <?php endif; ?>
```

hope this helps :)

**Comment by xillibit** [comment]
Try now

**Comment by 810** [comment]
i have updated the code and style: see https://github.com/Kunena/Kunena-Forum/pull/3519

**Comment by 810** [comment]
closing this one, check other pr

**Pull request closed without merging**
