### PR TITLE
Add some setting options for "User can Edit" and "User can Delete" #5695

### PR DESCRIPTION
**Pull request by xillibit**
Pull Request for Issue # .

### CODE REVIEW

**Comment by rich20** [comment]
- [x] User edits = Never
- [x] User edits = Only for the last message of the topic
- [x] User edits = Yes, when no replies
- [ ] User edits = Always (Only the last message of the topic can edited)
- [ ] User edits = Only for the **first** message of the topic (Only the last message of the topic can edited)

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] User edits = Never
- [x] User edits = Only for the last message of the topic
- [x] User edits = Yes, when no replies
- [x] User edits = Always
- [ ] User edits = Only for the **first** message of the topic (Only the last message of the topic can edited)

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] User edits = Never
- [x] User edits = Only for the last message of the topic
- [x] User edits = Yes, when no replies
- [x] User edits = Always
- [x] User edits = Only for the first message of the topic

All works correct now

**Pull request merged**
