### PR TITLE
Add module position in custom content

### PR DESCRIPTION
**Pull request by sshcli**
#### Summary of Changes 
 
bad
good

### CODE REVIEW

**Comment by sshcli** [comment]
There are some limitations while inserting a module inside a joomla article and then making the bbcode reference from the custom content menu `[article]articleid[/article] `

This PR is for enable the option to insert modules straight in the custom content menu (Without Joomla articles)

**Comment by rich20** [comment]
Is the double cc on the word "content" wanted or a typo?

**Comment by sshcli** [comment]
> Is the double cc on the word "content" wanted or a typo?

Wanted.
The first **C** is the short key for **custom**

Of course this can be changed if cause confusions, I can use the long phrase.
Just tell me, and I will change it right away.

**Comment by rich20** [comment]
Yes, cconent is logical, but gives the impression of a typo. But it needs not a long phrase. Maybe it would enough kunena_c_content_top/bottom

**Comment by 810** [comment]
please change to `kunena_custom_top` and `kunena_custom_bottom`

**Comment by rich20** [comment]
> please change to 'kunena_custom_top' and 'custom_custom_bottom'

I think, you meant 'kunena_custom_top' and 'kunena_custom_bottom'

**Comment by sshcli** [comment]
Done

**Pull request merged**
