### PR TITLE
[K3.0.9] Fix error message on none empty message

### PR DESCRIPTION
**Pull request by 810**
before a normal user can't do

[confidential]some text[/confidential]

Then he get the error that the message is empty

### CODE REVIEW

**Comment by rich20** [comment]
In principle it works. But when a normal user edit his confidential informations, then the message will deleted.
Message
The message has been successfully deleted.

**Comment by 810** [comment]
Try now, 

I have removed the check on empty message, so users can't delete their topic. 
This fixed an other issue, that users can delete their message even if the setting is disabled.

But we need to add a function on backend at recount messages, with a new option: remove empty messages

**Comment by rich20** [comment]
- [x] Success

> This fixed an other issue, that users can delete their message even if the setting is disabled.
But we need to add a function on backend at recount messages, with a new option: remove empty messages

I also think so. The admin should decide whether he wants to delete blank posts.

**Comment by xillibit** [comment]
I'am not sure if it's good idea to do it in this way

**Comment by xillibit** [comment]
You can't just post a message with just confidential because people with haven't the right to see the confidential will see an empty message

**Comment by 810** [comment]
closing this issue for now.

**Pull request closed without merging**
